# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Egh6DLJ20orz4tgX2kadnIu4wtjo98_
"""

# 1.What is a List?

# A list is a collection of different kinds of values or items.
# Items in list are seperated by commas
# and enclosed in square brackets. List is mutable means changable we can update modify the list.
# List contain Ordered Datatype  it means that the items have a defined order, and that order will not change.
# Lists allow duplicate values
# we can use methods like append(), extend(), insert(), remove() in list
# list is the collection of heterogenous datatype
# To determine how many items a list has, use the len() function
# eg
list1 = [2,4,8,9,2,5,1,6]
list1

"""# New Section"""

# 2. What is a Tuple?

# Tuples are used to store multiple items in a single variable.
# A tuple is a collection of items which is ordered and unchangeable. means tuple is immutable we can not modify it
# Tuples are written with round brackets. and allow duplicate values.
# To determine how many items a tuple has, use the len() function
# eg
tuple1 = ("mango","banana","watermelon","chiku")
tuple1

# 3. What is the difference between List and Tuple?

# List is mutable or changable and Tuple is immutable or unchangeable
# List items enclosed in square brackets and tuple items are enclosed in round brackets
# List generally have a slightly larger memory overhead compared to tuples because of their mutability tuples are immutable, they generally use less memory compared to lists.
# List provide many build in method and tuples have less in build method
# List is useful for insertion and deletion operation and tuple is useful for read only operation like accessing elements

# 4. Python Program to find the largest element in the list

list1 = [4,23,87,45,19,34,7,49]
print("The largest number is:",max(list1))

# 5. Python program to interchange first and last elements in a list.

def swaplist(newlist):
  newlist[0],newlist[-1] =  newlist[-1],newlist[0]
  return newlist

newlist = [24,66,86,32,58,45,57,97]
print(swaplist(newlist))

# 6. Python program to swap two elements in a list

def swap(lis,pos1,pos2):
  temp = lis[pos1]
  lis[pos1] = lis[pos2]
  lis[pos2] = temp
  return lis

List = [4,5,2,7,1,3,8,6,9]
pos1,pos2 = 1,2
print(swap(List,pos1-1,pos2-1))

# 7. Python program to Reverse a List

def reverselist(newlist):
  newlist = list1[::-1]
  return newlist
list1 = [23,54,67,93,14,34,65,78]
print(reverselist(list1))

# 8. Python program to count occurrences of an element in a list

list1 = [2,1,4,3,1,5,8,1,9,6,1]
num = 1
x = [j for i,j in enumerate(list1) if j == num]
print(f"the element {num} is occurres at {len(x)} times")

# 9. Python program to find the sum of elements in a list

list1 = [3,4,5,7,8,9]
total = sum(list1)
print("The sum of elements in a list is:",total)

# 10. Python program to Multiply all numbers in the list

def multiplylist(mylist):
  result = 1
  for i in mylist:
    result = i*result
  return result

list1 = [2,3,4]
list2 = [6,7,1]
print(multiplylist(list1))
print(multiplylist(list2))

# 11. What are the ways to find the length of a list

list1 = [3,4,5,6,7,8,9]
x = len(list1)
print(" the length of a list is:",x)

# 12. Python program to find the smallest and largest number in a list (Withoutmin-max function)

list1 = [37,57,83,38,92,73,58,35,48]
x = list1.sort()
print("smallest item in a list is:",list1[0])
print("largest item in a list is:",list1[-1])

# 13.Python Program to find the area of a circle

def area(r):
  pi = 3.14
  return pi*(r*r)

print("Area of Circle is:",area(5))

# 14. Take inputs from the user to make a list. Again take one input from the user and search it in the list and delete that element, if found. Iterate over a list using for loop.



user_list = input("Enter elements separated by space: ").split()


element_to_delete = input("Enter element to delete: ")

if element_to_delete in user_list:
    user_list.remove(element_to_delete)
    print(f"'{element_to_delete}' deleted from the list.")
else:
    print(f"'{element_to_delete}' not found in the list.")
print("Updated list:")
for item in user_list:
    print(item)

# 15. You are given a list of integer elements. Make a new list that will store a square of elements of the previous list. (With and without list comprehension)
# i. Input_list = [2,5,6,12]
# ii. Output_list = [4,25,36,144]

# Without list comprehension
Input_list = [2,5,6,12]
Output_list = []
for i in Input_list:
  x = i**2
  Output_list.append(x)
Output_list

# with list comprehension

Input_list = [2,5,6,12]
Output_list = [i**2 for i in Input_list]
Output_list

# 16. WAP to create two lists, one containing all even numbers and the other containing all odd numbers between 0 to 151

even_list = []
odd_list = []
for i in range(0,151):
  if i%2 == 0:
    even_list.append(i)
  elif i%2 == 1:
    odd_list.append(i)
print("Even List",even_list)
print("Odd List",odd_list)

# 17. Python program to Count Even and Odd numbers in a List

list1 = [3,5,9,35,32,45,64,57,74,79,58,34,89]
even_list, odd_list = 0,0
for i in list1:
  if i%2==0:
    even_list+=1
  else:
    odd_list+=1

print("Count Even numbers in a List",even_list)
print("Count Odd numbers in a List",odd_list)

# 18. WAP to make new lists, containing only numbers which are divisible by 4,6,8, 10, 3, 5, 7, and 9 in separate lists for range(0,151)

def newlist(num_range):
  divisible_by_4 = []
  divisible_by_6 = []
  divisible_by_8 = []
  divisible_by_10 = []
  divisible_by_3 = []
  divisible_by_5 = []
  divisible_by_7 = []
  divisible_by_9 = []

  for i in num_range:
    if i%4==0:
      divisible_by_4.append(i)
    if i%6==0:
      divisible_by_6.append(i)
    if i%8==0:
      divisible_by_8.append(i)
    if i%10==0:
      divisible_by_10.append(i)
    if i%3==0:
      divisible_by_3.append(i)
    if i%5==0:
      divisible_by_5.append(i)
    if i%7==0:
      divisible_by_7.append(i)
    if i%9==0:
      divisible_by_9.append(i)

  return divisible_by_4, divisible_by_6,divisible_by_8,divisible_by_10,divisible_by_3,divisible_by_5,divisible_by_7,divisible_by_9
num_range = range(0,151)

result = newlist(num_range)

divisors = [4, 6, 8, 10, 3, 5, 7, 9]
for i, values in enumerate(result):
    print(f"Numbers divisible by {divisors[i]}: {values}")

# 19. From a list containing ints, strings, and floats, make three lists to store them separately.

list1 = [2,5,9.4,'Ball',2.3,'Bat',3.4,1,'Cat']
ints_list = []
str_list = []
float_list = []

for i in list1:
  if isinstance(i,int):       #The isinstance() function returns True if the specified object
    ints_list.append(i)       # is of the specified type, otherwise False .
  elif isinstance(i,str):
    str_list.append(i)
  elif isinstance(i,float):
    float_list.append(i)

print("Integers:", ints_list)
print("String:", str_list)
print("Floats:", float_list)

# 20. What’s The Difference Between The Python append() and extend() Methods?

# append() is used to add a single element to the end of the list.
# extend() is used to add elements from an iterable to the end of the list

# python append() method
list1 = [3,4,5,6,7]
list1.append([10,20,30,40])
list1

# python extend() method
list1 = [3,4,5,6,7]
list1.extend([10,20,30,40])
list1

# 21. Write a Python program to append a list to the second list

list1 = [5,6,7,8,9]
list2 = [10,20,30,40,50]
list2.append(list1)

print("List1",list1)
print("List2",list2)

# 22. Write a Python program to find the third-largest number in a list

list1 = [3,6,8,20,53,59,32,,62,75]
length = len(list1)
sorted_list = list1.sort()
print("Length of list is:",length)
print("Third-largest number in a list",list1[length-3])

# 23. Write a Python program to get the frequency of the elements in a list.

from collections import Counter

list1 = [4,3,9,7,1,4,5,8,9,1,5,2,8,4,5,1]
frequency = Counter(list1)
print("frequency of the elements in a list",frequency)

# 24. Write a Python program to check whether a list contains a sublist
list1 = [2,3,6,7,8,5,4,9]
sublist = [6,7,8,5]

for i in range(len(list1)-len(sublist)+1):
  if list1[i:i+len(sublist)] == sublist:
    print("The sublist is present in the main list.")
    break
else:
  print("The sublist is not present in the main list.")

# 25. Write a Python program to generate all sublists of a list

original_list = [2, 3, 4, 9]
sublists_list = []
for i in range(len(original_list)):
    for j in range(i + 1, len(original_list) + 1):
        sublists_list.append(original_list[i:j])

print(sublists_list)

# 26. Write a Python program to find common items from two lists

list1 = [7,6,4,3,2]
list2 = [3,5,6,7,9,1]
common_item = []
for item in list1:
  if item in list2:
    common_item.append(item)
print(" common items from two lists is:",common_item)

#27. How to flatten a list in python?

list1 = [[1,2,3],[4,5,6],[7,8,9]]
x = []
for item in list1:
  for sublist in item:
    x.append(sublist)
x

# 28. How to sort a list in ascending and descending order without using the sort function?

list1 = [3,46,54,63,5,55,42,14,89]
for i in range(0,len(list1)):
  for j in range(i+1,len(list1)):
    if list1[i] >= list1[j]:
      list1[i],list1[j] =  list1[j],list1[i]
print("Sorted list in ascending order",list1)
print("Sorted list in descending order",list1[::-1])

# 29. How to sort a tuple?

tuple1 = (6,9,4,2,1,3,8)
sorted_tuple = tuple(sorted(tuple1))
sorted_tuple

# 30. Write a Python program to convert a list of multiple integers into a single integer  a. [11, 33, 50] >>> 113350


list1 = [11,33,50]
x = ''.join(map(str,list1))
result = int(x)
print(result)

# 31. Difference between del and clear?

# del is a general-purpose statement or keyword in python used to delete elements from memory.
list1 = [3,4,5,7,8,9]
del list1[2]
list1

# The clear() method removes all the elements from a list.
list1 = [3,4,5,7,8,9]
list1.clear()
list1

# 32. Difference between remove and pop?

# The remove() method removes the first matching value from the list.
list1 = [30,40,50,70,80,50,90]
list1.remove(50)
list1

# The pop() method like del deletes value at a particular index.
list1 = [30,40,50,70,80,50,90]
list1.pop(2)
list1

# 33. Difference between indexing and Slicing?


# Indexing refers to accessing a specific item in a sequence
list1 = [30,40,50,70,80,50,90]
index = list1[2]
index

# Slicing is the process of accessing a sub-sequence of a sequence by specifying a starting and ending index
list1 = [30,40,50,70,80,50,90]
list1[2:5]

# 34. Difference between sort and sorted?

#sort()function in Python is a method of list class and can only be used with lists.
list1 = [30,40,70,80,50,90]
list1.sort()
list1

# sorted() method sorts the given sequence as well as set and dictionary either in ascending order or in descending order
list1 = [30,40,70,80,50,90]
x = sorted(list1)
x

# 35. Difference between reverse and reversed?

# reverse() function in Python List is used to reverse the elements in the list
# list1 = [43,15,46,34,78,22,43,27,89]
# list1.reverse()
# list1

# reversed() function takes a sequence and returns the reversed iterator object.
list1 = [43,15,46,34,78,22,43,27,89]
x = reversed(list1)

y = []
for i in x:
  y.append(i)
y

# 36. Difference between copy and deep copy?

#  Shallow Copy() stores the copy of the original object and points the references to the objects.
# A shallow copy is faster.


list1 = [43,15,46,34,78,22,43,27,89]
list2 = list1.copy()
print("List1",list1)
print("List2",list2)


# Deep copy() stores the copy of the original object and recursively copies the objects as well.
# Deep copy is comparatively slower.


import copy
list1 = [43,15,46,34,78,22,43,27,89]
list2 = copy.deepcopy(list1)
list2[2] = 'python'
print("List1",list1)
print("List2",list2)



# 37. How to check whether the list is empty or not?

list1 = []
if not list1:
  print("List is empty")
else:
  print("List is not empty")

# 38. How to concatenate two lists?

list1 = [3,4,5,6,7]
list2 = [10,20,30,40,50]
result = list1+list2
print("concatenation of two lists:",result)

# 39. How to find the occurrences of an element in the python list?

list1 = [2,3,6,2,7,9,2,5,8,4,2]
item = 2
result = list1.count(item)
print(result)

# 40. How to flatten a list in python?

list1 = [[2,3,4],[6,7,8],[20,30,40]]
x = []
for i in list1:
  for j in i:
    x.append(j)
x

# *************************** PRACTICE ***********************************

# 1.What is a List?

a = [2,3,4,'Pyton','data']
a

# 2. What is a Tuple?

a = ('mango','banana','pineapple')
a

# 3. What is the difference between List and Tuple?

# 4. Python Program to find the largest element in the list

list1 = [4,23,87,45,19,34,7,49]
max = max(list1)
print("largest element in the list is:",max)

# 5. Python program to interchange first and last elements in a list.

list1 = [4,23,87,45,19,34,7,49]
list1[0],list1[-1] = list1[-1],list1[0]

print(list1)

def swapcase(list1):
  list1[0],list1[-1] = list1[-1],list1[0]

list1 = [4,23,87,45,19,34,7,49]
swapcase(list1)
print(list1)

# 6. Python program to swap two elements in a list

list1 = [4,23,87,45,19,34,7,49]

temp = list1[2]
list1[2] = list1[-3]
list1[-3] = temp

print(list1)

list1 = [4,23,87,45,19,34,7,49]

temp = list1[-3]
list1[-3] = list1[-2]
list1[-2] = temp

print(list1)

# 7. Python program to Reverse a List

def reverselist(list1):
  n = list1[::-1]
  return n

list1 = [9,8,7,6,5,4,3]
reverselist(list1)

# 8. Python program to count occurrences of an element in a list

list1 = [4,5,6,9,5,2,3,5,6,8,4,5,1,3]
num = 5

result = [v for i,v in enumerate(list1) if v==num]
print(f"Occurance of number {num} is {len(result)} times ")

# 9. Python program to find the sum of elements in a list

list1 = [4,5,6,7,8,9,10]
x = sum(list1)
print(f"Sum of elements in the list is {x}")

# 10. Python program to Multiply all numbers in the list

x = [3,4,5,6]
result = 1
for i in x:
  result = result*i
print(f"Multiplication of all numbers in the list is: {result}")

# 11. What are the ways to find the length of a list

x = [3,4,5,6,7,8]

length = len(x)
print(f"The length of a list is: {length}")

# without fuc

x = [3,4,5,6,7,8]
count = 0
for i in x:
  count+=1

print(f"The length of a list is: {count}")

# 12. Python program to find the smallest and largest number in a list (Withoutmin-max function)

x = [13,42,53,65,17,86,79,45]
result = sorted(x)

smallest = result[0]
largest = result[-1]

print(f"Smallest number is: {smallest}")
print(f"Largest number is: {largest}")

# 13.Python Program to find the area of a circle

import math
r = 5
area = math.pi *  r**2
print(f"Area of Circle is: {(area)}")

# How to flatten a list in python?

list1 = [[[2,3,4],[5,6,7],[8,9,10]]]
x = []
for item in list1:
  for i in item:
    for j in i:
      x.append(j)
x

# How to find the occurrences of an element in the python list?

list1 = [2,1,3,4,1,5,1,3,9,1]
num = 1
result = list1.count(num)
result

# How to concatenate two lists?

list1 = [2,3,4,5,6]
list2 = [11,22,33,44,55]
result = list1+list2
print(result)

# How to check whether the list is empty or not?

list1 = []
if not list1:
  print("List is empty")
else:
  print("List is not empty")

# Difference between reverse and reversed?

list1 = [2,3,4,5,6,7]
x = reversed(list1)
y = []
for i in x:
  y.append(i)
y

# Difference between sort and sorted?

list1 = [2,5,6,3,4,1,8]
# list1.sort()  # used to sort items in the list
# list1
x = sorted(list1)
x

# Difference between indexing and Slicing?

list1 = [2,5,6,3,4,1,8]
# x = list1[2] # indexing : accessing specific item in sequence
# x
list1[2:5]
# Slicing : process of accessing  subsequence of sequence either in ascending/descending order

list1 = [2,3,4,5,6]
list2 = list1.copy()

print("List1:",list1)
print("List2:",list2)

import copy

list1 = [2,3,4,5,6]
list2 = copy.deepcopy(list1)
list2[0] = "python"

print("List1:",list1)
print("List2:",list2)

