# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVk359YoJGsH-f282hGIEec7y3Zarx8l
"""

# 10. Write a program to print every character of a string entered by the user in a
# new line using a loop

string = input("Enter a string ")
for i in string:
  print(i)

# 11. Write a program to find the length of the string "machine learning" with and
# without using len function.

# with
# string = "machine learning"
# result = len(string)
# print("length of the string is:",result)


# without
string = "machine learning"
count = 0
for char in string:
  count+=1
print("length of the string is:",count)

# 12. Write a program to check if the word 'orange' is present in the "This is orange
# juice".

string = "This is orange juice"
word = "orange"
if word in string:
  print(f"{word} is present in string")
else:
  print(f"{word} is not present in string")

# 13. Write a program to find the number of vowels, consonants, digits, and white
# space characters in a string.

string = input("Enter a string:")
vowels = 0
consonants = 0
digits = 0
white_space = 0
Vowels = "AEIOUaeiou"

for char in string:
  if char.isalpha():
    if char in Vowels:
      vowels+=1
    else:
      consonants+=1
  elif char.isdigit():
    digits+=1
  else:
    white_space+=1

print("vowels",vowels)
print("consonants",consonants)
print("digits",digits)
print("white_space",white_space)

# 14. Write a Python program to count Uppercase, Lowercase, special character,
# and numeric values in a given string.

string = input("Enter a string ")
uppercase = 0
lowercase = 0
special_char = 0
num_val = 0

for char in string:
  if char.isupper():
    uppercase+=1
  elif char.islower():
    lowercase+=1
  elif char.isdigit():
    num_val+=1
  else:
    special_char+=1

print("uppercase",uppercase)
print("lowercase",lowercase)
print("special_char",special_char)
print("num_val",num_val)

# 15. Write a program to make a new string with all the consonants deleted from the
# string "Hello, have a good day".

string = "Hello, have a good day"
Vowels = "AEIOUaeiou"
result = " "
for char in string:
  if char in Vowels:
    result+=char
print(result)

# 16. Write a Python program to remove the nth index character from a non-empty string.

def remove_nth_index(string,n):
  return string[:n]+string[n+1:]

string = "python"
n = 3
print(remove_nth_index(string,n))

# 17. Write a Python program to change a given string to a new string where the
# first and last characters have been exchanged.


string = "Hello, have a good day"
if len(string)<2:
  print(string)
else:
  print(string[-1]+string[1:-1]+string[0])

# 18. Write a Python program to count the occurrences of each word in a given sentence.

from collections import Counter
sentence = input("Enter a sentence")
word = sentence.split()

print(Counter(word))

# 19. How do you count the occurrence of a given character in a string?


string = input("Enter a string: ")
char_to_count = input("Enter a char to count: ")

count = 0
for char in string:
  if char == char_to_count:
    count+=1
print(f"character {char_to_count} occurred {count} times")

# 20. Write a program to find last 10 characters of a string?

string = input("Enter a string: ")
result = string[-10:]
print(result)

# 21. WAP to convert a given string to all uppercase if it contains at least 2
# uppercase characters in the first 4 characters.

string = input("Enter a string: ")
count = 0
for char in string[:4]:
  if char.isupper():
    count+=1

if count >= 2:
  print(string.upper())
else:
  print(string)

# 22. Write a Python program to remove a newline in Python.

text = "Hello World\n"
result = text.strip()
print(result)

# 23. Write a Python program to swap commas and dots in a string
# ○ Sample string: "32.054,23"
# ○ Expected Output: "32,054.23"


string = "32.054,23"
string1 = string.replace(".","*")
string2 = string1.replace(",",".")
string3 = string2.replace("*",",")
print(string3)

# 24. Write a Python program to find the first repeated character in a given string

def first_reapeating_char(string):
  for char in string:
    if string.count(char)>1:
      return f"first reapeating char is {char}"
  return "No reapeating char found"

first_reapeating_char("programming")

# 25. Write a Python program to find the second most repeated word in a given string

string = "apple banana apple orange banana apple banana"
words = string.split()
freq = {}
for w in words:
  freq[w] = freq.get(w,0)+1

result = sorted(freq,key=freq.get,reverse=True)
result[1]

# 26. Python program to Count Even and Odd numbers in a string

string = "1 2 3 4 5 6 7"
even_count = 0
odd_count = 0
num = string.split()
for i in num:
  if int(i)%2 == 0:
    even_count+=1
  elif int(i)%2 != 0:
    odd_count+=1
print("even_count",even_count)
print("odd_count",odd_count)

# 27. How do you check if a string contains only digits?

string = "123456"
if string.isdigit():
  print("string contains only digits")
else:
  print("string does not contains only digits")

# 28. How do you remove a given character/word from String?

# remove word
# string = "python is easy to learn"
# result = string.replace("easy","")
# print(result)

#remove char
string = "python is easy to learn"
result = string.replace("p","")
print(result)

# 29. Write a Python program to remove the characters which have odd index
# values of a given string

def char_to_remove(string):
  result = ""
  for char in range(len(string)):
    if char%2 == 0:
      result+=string[char]
  return result

string = "programming"
char_to_remove(string)

# 30. Write a Python function to reverses a string if its length is a multiple of 5

string = "Python and data"
if len(string)%5==0:
  print(string[::-1])
else:
  print(string)

# 31. Write a Python program to format a number with a percentage(0.05 >> 5%)

num = 0.05
percentage = num*100
print(f"{percentage}%")

# 32. Write a Python program to reverse words in a string

string = "python is easy to learn"
result = string.split()
x = " ".join(result[::-1])
x

# 33. Write a Python program to swap cases of a given string

string = "PYthON and DAta SCIence"
result = string.swapcase()
print(result)

# 34. Write a Python program to remove spaces from a given string

string = "python and data science"
x = string.replace(" ","")
x

# 35. Write a Python program to remove duplicate characters of a given string

string = "programming"
result = ""
for char in string:
  if char not in result:
    result+=char
print(result)

# 36. Write a Python Program to find the area of a circle

r = 2.43
area = 3.14*r*r
print(area)

# 37. Python Program to find Sum of squares of first n natural numbers

n = int(input("Enter a number "))
sum_sqr = 0
for i in range(1,n+1):
  sum_sqr += i**2
print(f"squares of first {n} natural numbers is",sum_sqr)

# 38. Python Program to find cube sum of first n natural numbers

n = int(input("Enter a number: ")) #10
sum_cube = 0
for i in range(1,n+1):
  sum_cube+=i**3
print(f"cube of first {n} natural numbers is",sum_cube)

# 39. Python Program to find simple interest and compound interest

P = float(input("Enter Principal Amount: "))
R = float(input("Enter Rate of Interest: "))
T = float(input("Enter Time (in years): "))

SI = (P * R * T) / 100

CI = P * (1 + R/100) ** T - P

print("Simple Interest:", SI)
print("Compound Interest:", CI)

# 40. Python program to check whether a number is Prime or not

# Prime no are the numbers that are divisible by 1 and the number itself

n = int(input("Enter a number: "))

if n>1:
  for i in range(2,n):
    if n%i == 0:
      print("Not prime")
      break
  else:
    print("Prime")
else:
  print("Not prime")