# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_VRGKeX4zOfwPQtrf0Alp6ChtJg-PnI
"""

# 1.

# *
# * *
# * * *
# * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end = " ")
  print()

# 2.

#         *
#       * *
#     * * *
#   * * * *
# * * * * *

# 1 method
n=6
for i in range(1,n):
  for j in range(1,n-i):
    print(" ",end=" ")
  for k in range(i):
    print("*",end=" ")
  print()


# 2 method
# n=5
# space=n-1
# for i in range(0,n):
#   for j in range(0,space):
#     print(" ",end=' ')
#   space=space-1
#   for j in range(0,i+1):
#     print("*",end=' ')
#   print("\r")

# 3.
#      *
#     * *
#    * * *
#   * * * *
#  * * * * *

n=5
space=n-1
for i in range(0,n):
  for j in range(0,space):
    print(end=' ')
  space=space-1
  for j in range(0,i+1):
    print("*",end=' ')
  print("\r")

# 4.

# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=' ')
  print()

5.
# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

n=5
x=1
for i in range(1,n+1):
  for j in range(1,i+1):
    print(x,end=' ')
    x+=1
  print()

# 6.
# A [Use ASCII Values]
# B B
# C C C
# D D D D
# E E E E E


n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=' ')
  x+=1
  print()

# 7.
# A
# B C
# D E F
# G H I J
# K L M N O

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=' ')
    x+=1
  print()

# 8.
# K
# K K
# K K K
# K K K K
# K K K K K

n=5
for i in range(1,n+1):
  for j in range(i):
    print("K",end=' ')
  print()

# 9.
# A
# A B
# A B C
# A B C D
# A B C D E

# n=5
# x=65
# for i in range(n):
#   for j in range(i+1):
#     print(chr(x+j),end=' ')
#   print()

n=5
x=65
for i in range(n+1):
  for j in range(i):
    print(chr(x+j),end=" ")
  print()

# 10.
# P
# Py
# Pyt
# Pyth
# Pytho
# Python


string="python"
for i in range(1,len(string)+1):
  print(string[:i])

# 11.
# 1 1 1 1 1
# 2 2 2 2
# 3 3 3
# 4 4
# 5

n=5
for i in range(1,n+1):
  for j in range(n,i-1,-1):
    print(i,end=' ')
  print()

# 12.
# 6 6 6 6 6 6
# 5 5 5 5 5
# 4 4 4 4
# 3 3 3
# 2 2
# 1

n=6
for i in range(n,0,-1):
  for j in range(i):
    print(i,end=' ')
  print()

# 13.
# 0 1 2 3 4 5
# 0 1 2 3 4
# 0 1 2 3
# 0 1 2
# 0 1

n=5
for i in range(n,0,-1):
  for j in range(i+1):
    print(j,end=' ')
  print()

# 14.
# 1
# 2 3
# 4 5 6


num = 1
for i in range(3):
    for j in range(i + 1):
      print(num, end=" ")
      num += 1
    print()

# 15.
# 6 5 4 3 2 1
# 5 4 3 2 1
# 4 3 2 1
# 3 2 1
# 2 1
# 1

n=6
for i in range(n,0,-1):
  for j in range(i,0,-1):
    print(j,end=' ')
  print()

# 16.
# 1
# 3 3
# 5 5 5
# 7 7 7 7
# 9 9 9 9 9

num=1
for i in range(1,6):
  for j in range(i):
    print(num,end=' ')
  num+=2
  print()

# 17.
#         1
#       1 2
#     1 2 3
#   1 2 3 4
# 1 2 3 4 5


for i in range(5):
    for j in range(4 - i):
        print(" ", end=" ")
    for k in range(1, i + 2):
        print(k, end=" ")

    print()

# 18.
# 1 2 3 4 5
# 2 2 3 4 5
# 3 3 3 4 5
# 4 4 4 4 5
# 5 5 5 5 5

for i in range(1, 6):
    for j in range(1, 6):
        if j <= i:
            print(i, end=" ")
        else:
            print(j, end=" ")
    print()

# 19.
# 1
# 2 4
# 3 6 9
# 4 8 12 16
# 5 10 15 20 25
# 6 12 18 24 30 36
# 7 14 21 28 35 42 49


for i in range(1, 8):
    for j in range(1, i + 1):
        print(i * j, end=" ")
    print()

# 20.
# 1
# 2 1
# 4 2 1
# 8 4 2 1
# 16 8 4 2 1
# 32 16 8 4 2 1
# 64 32 16 8 4 2 1
# 128 64 32 16 8 4 2 1

for i in range(0, 8):
    for j in range(i, -1, -1):
        print(2**j, end=" ")
    print()

# 21.
# * * * * * * * * * * * * * *
# * * * * * *     * * * * * *
# * * * * *         * * * * *
# * * * *             * * * *
# * * *                 * * *
# * *                     * *
# *                         *

# 22.
# *
# * *
# * * *
# * * * *
# * * * * *
# * * * * * *
# * * * * * * *
# * * * * * *
# * * * * *
# * * * *
# * * *
# * *
# *

n = 7

for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()

for i in range(n-1,0,-1):
    for j in range(i):
        print("*", end=" ")
    print()

# 23.
# *
# * *
# * * *
# * * * *
# * * * * *
# * * * * * *


# * * * * * *
# * * * * *
# * * * *
# * * *
# * *
# *


n = 6

for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()
print()

for i in range(n, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

# 1.
# *
# * *
# * * *
# * * * *
# * * * * *




# 2.
# *
# * *
# * * *
# * * * *
# * * * * *





# 3.
# *
# * *
# * * *
# * * * *
# * * * * *




# 4.
# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5





# 5.
# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

# *
# * *
# * * *
# * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end=" ")
  print()

#         *
#       * *
#     * * *
#   * * * *
# * * * * *


n=6
for i in range(1,n):
  for j in range(1,n-i):
    print(" ",end=" ")
  for k in range(i):
    print("*",end=" ")
  print()

# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

n=5
x=1
for i in range(1,n+1):
  for j in range(1,i+1):
    print(x,end=" ")
    x+=1
  print()

# A
# B B
# C C C
# D D D D
# E E E E E


n=5
x=65
for i in range(1,n+1):
  for j in range(i):
    print(chr(x),end=" ")
  x+=1
  print()

# A
# B C
# D E F
# G H I J
# K L M N O

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
    x+=1
  print()

# K
# K K
# K K K
# K K K K
# K K K K K

n=5
for i in range(1,n+1):
  for j in range(i):
    print("k",end=" ")
  print()

# A
# A B
# A B C
# A B C D
# A B C D E

n=5
x=65
for i in range(1,n+1):
  for j in range(i):
    print(chr(x+j),end=" ")
  print()

# P
# Py
# Pyt
# Pyth
# Pytho
# Python

string = "python"
for i in range(1,len(string)+1):
  print(string[:i])

# 1 1 1 1 1
# 2 2 2 2
# 3 3 3
# 4 4
# 5

n=5
for i in range(1,n+1):
  for j in range(n,i-1,-1):
    print(i,end=" ")
  print()

# 6 6 6 6 6 6
# 5 5 5 5 5
# 4 4 4 4
# 3 3 3
# 2 2
# 1

n=6
for i in range(n,0,-1):
  for j in range(i):
    print(i,end=" ")
  print()

# 0 1 2 3 4 5
# 0 1 2 3 4
# 0 1 2 3
# 0 1 2
# 0 1

n=5
for i in range(n,0,-1):
  for j in range(i+1):
    print(j,end=' ')
  print()

# 1
# 2 3 4
# 5 6 7 8 9

n=1
rows=3
for i in range(1,rows+1):
  for j in range(i*2-1):
    print(n,end=" ")
    n+=1
  print()

# 6 5 4 3 2 1
# 5 4 3 2 1
# 4 3 2 1
# 3 2 1
# 2 1
# 1

n=6
for i in range(n,0,-1):
  for j in range(i,0,-1):
    print(j,end=' ')
  print()

# *
# * *
# * * *
# * * * *
# * * * * *


n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end=" ")
  print()

#         *
#       * *
#     * * *
#   * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(n,i-1,-1):
    print(" ",end=" ")
  for k in range(i):
    print("*",end=" ")
  print()

# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

n=5
x=1
for i in range(1,n+1):
  for j in range(1,i+1):
    print(x,end=" ")
    x+=1
  print()

# A
# B B
# C C C
# D D D D
# E E E E E

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
  x+=1
  print()

# *
# * *
# * * *
# * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end=" ")
  print()

#         *
#       * *
#     * * *
#   * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(n,i-1,-1):
    print(" ",end=" ")
  for k in range(i):
    print("*",end=" ")
  print()

# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

n=5
x=1
for i in range(1,n+1):
  for j in range(1,i+1):
    print(x,end=" ")
    x+=1
  print()

# A
# B B
# C C C
# D D D D
# E E E E E


n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
  x+=1
  print()

# A
# B C
# D E F
# G H I J
# K L M N O

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
    x+=1
  print()

# K
# K K
# K K K
# K K K K
# K K K K K

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print("K",end=" ")
  print()

# A
# A B
# A B C
# A B C D
# A B C D E

n=5
x=65
for i in range(n):
  for j in range(i+1):
    print(chr(x+j),end=" ")
  print()

# P
# Py
# Pyt
# Pyth
# Pytho
# Python

string = "Python"
for i in range(1,len(string)+1):
  print(string[:i])

# 1 1 1 1 1
# 2 2 2 2
# 3 3 3
# 4 4
# 5

n=6
for i in range(1,n+1):
  for j in range(n,i,-1):
    print(i,end=" ")
  print()

# 6 6 6 6 6 6
# 5 5 5 5 5
# 4 4 4 4
# 3 3 3
# 2 2
# 1

n=6
for i in range(n,0,-1):
  for j in range(i):
    print(i,end=" ")
  print()

# 0 1 2 3 4 5
# 0 1 2 3 4
# 0 1 2 3
# 0 1 2
# 0 1


n=5
for i in range(n,0,-1):
  for j in range(i+1):
    print(j,end=" ")
  print()

# 1
# 2 3 4
# 5 6 7 8 9

n=1
row=3
for i in range(1,row+1):
  for j in range(2*i-1):
    print(n,end=" ")
    n+=1
  print()

# 6 5 4 3 2 1
# 5 4 3 2 1
# 4 3 2 1
# 3 2 1
# 2 1
# 1

n=6
for i in range(n,0,-1):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()

# *
# * *
# * * *
# * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end=" ")
  print()

#         *
#       * *
#     * * *
#   * * * *
# * * * * *

n=5
for i in range(1,n+1):
  for j in range(n,i,-1):
    print(" ",end=" ")
  for k in range(i):
    print("*",end=" ")
  print()

# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

n=5
x=1
for i in range(1,n+1):
  for j in range(1,i+1):
    print(x,end=" ")
    x+=1
  print()

# A
# B B
# C C C
# D D D D
# E E E E E

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
  x+=1
  print()

# A
# B C
# D E F
# G H I J
# K L M N O

n=5
x=65
for i in range(1,n+1):
  for j in range(1,i+1):
    print(chr(x),end=" ")
    x+=1
  print()

# K
# K K
# K K K
# K K K K
# K K K K K

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print("K",end=" ")
  print()

# A
# A B
# A B C
# A B C D
# A B C D E

n=5
x=65
for i in range(n+1):
  for j in range(i):
    print(chr(x+j),end=" ")
  print()

# P
# Py
# Pyt
# Pyth
# Pytho
# Python

string = "Python"
for i in range(1,len(string)+1):
  print(string[:i])

# 1 1 1 1 1
# 2 2 2 2
# 3 3 3
# 4 4
# 5

n=6
for i in range(1,n+1):
  for j in range(n,i,-1):
    print(i,end=" ")
  print()

# 6 6 6 6 6 6
# 5 5 5 5 5
# 4 4 4 4
# 3 3 3
# 2 2
# 1

n=6
for i in range(n,0,-1):
  for j in range(i):
    print(i,end=" ")
  print()

# 0 1 2 3 4 5
# 0 1 2 3 4
# 0 1 2 3
# 0 1 2
# 0 1

n=5
for i in range(n,0,-1):
  for j in range(i+1):
    print(j,end=" ")
  print()

# 1
# 2 3 4
# 5 6 7 8 9

n=1
rows=3
for i in range(1,rows+1):
  for j in range(i*2-1):
    print(n,end=" ")
    n+=1
  print()

# 6 5 4 3 2 1
# 5 4 3 2 1
# 4 3 2 1
# 3 2 1
# 2 1
# 1

n=6
for i in range(n,0,-1):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()

# 1
# 3 3
# 5 5 5
# 7 7 7 7
# 9 9 9 9 9

num=1
for i in range(1,6):
  for j in range(1,i+1):
    print(num,end=" ")
  num+=2
  print()

#         1
#       1 2
#     1 2 3
#   1 2 3 4
# 1 2 3 4 5

n=5
for i in range(n):
  for j in range(4-i):
    print(" ",end=" ")
  for k in range(1,i+2):
    print(k,end=" ")
  print()

# 1
# 2 4
# 3 6 9
# 4 8 12 16
# 5 10 15 20 25
# 6 12 18 24 30 36
# 7 14 21 28 35 42 49


n=7
for i in range(1,n+1):
  for j in range(1,i+1):
    print(i*j,end=" ")
  print()

# *
# * *
# * * *
# * * * *
# * * * * *
# * * * * * *
# * * * * * * *
# * * * * * *
# * * * * *
# * * * *
# * * *
# * *
# *

n=7
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()
for i in range(n-1,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

# *
# * *
# * * *
# * * * *
# * * * * *
# * * * * * *


# * * * * * *
# * * * * *
# * * * *
# * * *
# * *
# *


n=6
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

print()


for i in range(n,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

