# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FeSjARqu2CE86FcYJWs_3hH39vU7oET
"""

# 1. Python program to sort Python Dictionaries by Keys

a = {'Sahil':34,'Suraj':39,'Isha':43,'Vaishnavi':32,'Rohan':46}
sorted_dict =  dict(sorted(a.items()))
sorted_dict

# 2. Python program to sort Python Dictionaries by Values

a = {'Sahil':34,'Suraj':39,'Isha':43,'Vaishnavi':32,'Rohan':46}
sorted_dict = dict(sorted(a.items(),key=lambda x:x[1]))
sorted_dict

# 3. Python program to find the sum of all items in a dictionary

dict1 = {'a':23,'b':42,'c':53,'d':56,'e':76,'f':28,'g':67}
print(" sum of all items in a dictionary is:",sum(dict1.values()))

# 4. Python program to remove a key from a dictionary

dict1 = {'a':23,'b':42,'c':53,'d':56,'e':76,'f':28,'g':67}
del dict1['c']
dict1

# 5. Python program to merge two Dictionaries

dict1 = {'a':23,'b':34,'c':12}
dict2 = {'x':45,'y':41,'z':52}

dict1.update(dict2)
print(dict1)

# 6. Program to create grade calculator in Python

print("Enter a marks obtained in 5 subjects")
sub1 = 44
sub2 = 67
sub3 = 73
sub4 = 95
sub5 = 58

total = sub1+sub2+sub3+sub4+sub5
avg = total/5

if avg>=90 and avg<=100:
  print("A1 grade")
elif avg>=80 and avg<=90:
  print("A2 grade")
elif avg>=70 and avg<=80:
  print("B1 grade")
elif avg>=60 and avg<=70:
  print("B2 grade")
elif avg>=50 and avg<=60:
  print("C1 grade")
elif avg>=40 and avg<=50:
  print("C2 grade")
else:
  print("Need more improvement in Academic")

# 7. Print anagrams together in Python using List and Dictionary

words = ['cat', 'dog', 'tac', 'god', 'act', 'arc', 'car']
anagrams = {}

for word in words:
  key =  "".join(sorted(word))
  if key in anagrams:
    anagrams[key].append(word)
  else:
    anagrams[key] = [word]

for i in anagrams.values():
  print(i)

# 8. Check if binary representations of two numbers are an anagram

num1 = int(input("Enter a first number "))
num2 = int(input("Enter a second number "))

str1 = bin(num1)[2:]
str2 = bin(num2)[2:]


if len(str1) != len(str2):
  print("They are not Binary Anagrams")
else:
  if sorted(str1) == sorted(str2):
    print("Its Binary representations of Anagram")
  else:
    print("Not anagram")

# 9. Python Counter to find the size of the largest subset of anagram words

from collections import Counter

words = ["eat", "tea", "tan", "ate", "nat", "bat"]

# Create sorted-word keys
keys = ["".join(sorted(word)) for word in words]

# Count anagram groups
count = Counter(keys)

# Size of the largest anagram subset
largest_subset_size = max(count.values())

print(largest_subset_size)

# 10. Python Dictionary to find mirror characters in a string

mirror_dict = {'A': 'A', 'B': 'd', 'C': 'C', 'D': 'b', 'E': 'E', 'F': 'F',
               'G': 'G', 'H': 'H', 'I': 'i', 'J': 'J', 'K': 'K', 'L': 'L',
               'M': 'M', 'N': 'N', 'O': 'O', 'P': 'q', 'Q': 'p', 'R': 'R',
               'S': 'S', 'T': 'T', 'U': 'U', 'V': 'V', 'W': 'W', 'X': 'X',
               'Y': 'Y', 'Z': 'Z', 'a': 'a', 'b': 'D', 'c': 'c', 'd': 'B',
               'e': 'e', 'f': 'F', 'g': 'G', 'h': 'H', 'i': 'I', 'j': 'J',
               'k': 'K', 'l': 'L', 'm': 'M', 'n': 'N', 'o': 'O', 'p': 'Q',
               'q': 'P', 'r': 'R', 's': 'S', 't': 'T', 'u': 'U', 'v': 'V',
               'w': 'W', 'x': 'X', 'y': 'Y', 'z': 'Z'}

input_str = input('Enter a string')

mirror_char = [mirror_dict[char] for char in  input_str if char in mirror_dict]

if mirror_char:
  print("Mirror char in the string: ",''.join(mirror_char))
else:
  print("No mirror char found in the string")

# 11. Counting the frequencies in a list using a dictionary in Python

list1 = [4,2,3,1,6,2,3,1,5,4,2,3,1]
dict1 = {}
for char in list1:
  if char in dict1:
    dict1[char]+=1
  else:
    dict1[char]=1

for key,value in dict1.items():
  print(f"{key}:{value} times")

# 12. Python program to convert a list of Tuples into Dictionary

list1 = [('Sahil', 10), ('Monika', 7), ('Krishna', 18), ('Rohit', 45)]
dict1 = {}
for items in list1:
  dict1[items[0]] = items[1]

print(dict1)

# 13. Scraping And Finding Ordered Words In A Dictionary using Python

# 14. Create a list of tuples from the given list having a number and its cube in each tuple

list1 = [3,4,5,6,7,8,9]

tuple_list = [(char,char**3) for char in list1]
print(tuple_list)

# 15. Sort a list of tuples by the second Item

list1 = [(2,7),(5,3),(9,6),(8,5),(7,4),(4,2)]

sorted_list = sorted(list1,key= lambda x:x[1])
print(sorted_list)

# 16. Python Program for Insertion Sort

def Insertion(arr1):
  n = len(arr1)

  for i in range(1,n): # 1234
    key = arr1[i]
    j = i-1

    while j>=0 and key<arr1[j]:
      arr1[j+1] = arr1[j]
      j-=1
    arr1[j+1] = key

arr1 = [40,25,20,10,30]
Insertion(arr1)
print("Sorted array is:",arr1)

# 17. Python Program for SelectionSort

def selection(arr1):
  n=len(arr1)

  for i in range(n-1):
    mini = i
    for j in range(i+1,n):
      if arr1[j]<arr1[mini]:
        mini = j
        arr1[i],arr1[mini] = arr1[mini],arr1[i]

arr1 = [24,41,33,42,76,17,83]
selection(arr1)
print("Selection sort of array is:",arr1)

# 18. Python Program for Bubble Sort

def bubble(arr1):
  n = len(arr1)
  for i in range(n):
    swapped = False
    for j in range(0,n-i-1):
      if arr1[j]>arr1[j+1]:
        arr1[j],arr1[j+1] = arr1[j+1],arr1[j]
        swapped = True
    if not swapped:
      break

arr1 = [50,20,10,40,30]
bubble(arr1)
print("Bubble sort is:",arr1)

# 19. Python Program for Merge Sort

def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    return sorted(left + right)

# Example
arr = [5, 3, 8, 4, 2]
print(merge_sort(arr))

# 20. Python Program for QuickSortSort

def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[0]   # choose first element as pivot
    left = [x for x in arr[1:] if x <= pivot]
    right = [x for x in arr[1:] if x > pivot]

    return quick_sort(left) + [pivot] + quick_sort(right)

# Example
arr = [10, 7, 8, 9, 1, 5]
print(quick_sort(arr))

