# -*- coding: utf-8 -*-
"""vel_Dict_Datatype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPmc-BnBO1QoQwRJIGesC_To06NbGQj1
"""

# Datatypes

# string : Immutable,ordered,Duplicates items are allowed, ' ', " ", '''char''', """char"""
# list   : Mutable,ordered,Duplicates items are allowed,[],list()
# tuple  : Immutable,ordered,Duplicates items are allowed,(),tuple(),(2,)
# set    : Mutable,Unordered,Duplicates items are not allowed, {3,4,5},set()
# Frozenset: Immutable, Unordered,Duplicates items are not allowed,frozenset({3,4}),frozenset()

# Dictionary

# It is collection of key and value pairs
# Mutable
# Ordered(3.7 version and more)
# Unordered(less than 3.7 version)
# Indexing and Slicing is not allowed
# Key can not be duplicate
# Values can be duplicate

# dictionary as value in dictionary
# we can not use dictionary object as a key in dict

# Dictionary Function

# get()         Returns the value of the specified key
# key() 	      Returns a list containing the dictionary's keys
# values()      Returns a list of all the values in the dictionary
# items()     	Returns a list containing a tuple for each key value pair
# update()     	Updates the dictionary with the specified key-value pairs
# pop()       	Removes the element with the specified key
# popitem()     Removes the last inserted key-value pair

dict1 = {'a':97}
print(len(dict1))
dict1

dict1 = {'a':97,'a':100}   # Key can not be duplicate
print(dict1)
len(dict1)

dict1 = {'a':97,'b':98,'c':99,'a':100}
print(dict1)
len(dict1)

dict1 = {'a':97,'b':98,'c':99,'a':100,'b':200}
print(dict1)
len(dict1)

dict1 = {'a':97,'b':98,'c':99,'a':100,'b':200}   # we can access value with the help of key
dict1['b']

dict1 = {'a':97,'b':98,'c':99,'a':100,'b':200}
dict1['a']

employee_details = {'Name':'Ajay',
                    'Age':24,
                    'Company':'TCS',
                    'Designation':'Data Analyst'}
employee_details

employee_details["Salary"] = 90000
employee_details

# If we want to add multiple key value then we have to use update() function

employee_details = {'Name':'Ajay',
                    'Age':24,
                    'Company':'TCS',
                    'Designation':'Data Analyst'}
employee_details.update({'Salary':60000,'Location':'Pune'})
employee_details

len(employee_details)

employee_details = {'TC10021':{'Name': 'Ajay',
                                'Age': 24,
                                'Company': 'TCS',
                                'Designation': 'Data Analyst',
                                'Salary': 60000,
                                'Location': 'Pune'},
                    'TC10022':{'Name': 'Anushka',
                                'Age': 27,
                                'Company': 'Wipro',
                                'Designation': 'Data Engineer',
                                'Salary': 50000,
                                'Location': 'Mumbai'}}
employee_details

len(employee_details)

employee_details = {'TC10021':{'Name': 'Ajay',
                                'Age': 24,
                                'Company': 'TCS',
                                'Designation': 'Data Analyst',
                                'Salary': 60000,
                                'Location': 'Pune'},
                    'TC10022':{'Name': 'Anushka',
                                'Age': 27,
                                'Company': 'Wipro',
                                'Designation': 'Data Engineer',
                                'Salary': 50000,
                                'Location': 'Mumbai'},
                    'TC10023':{'Name': 'Rohit',
                                'Age': 41,
                                'Company': 'AMADOCS',
                                'Designation': 'Data Scientist',
                                'Salary': 100000,
                                'Location': 'Delhi'}}
employee_details

employee_details['TC10023']

employee_details['TC10023']['Designation']

employee_details['TC10021']

employee_details['TC10021']['Salary']

employee_details

employee_details['TC10023']['Location'].replace('Delhi','Hydrabad')

employee_details['TC10023']['Location'] = employee_details['TC10023']['Location'].replace('Delhi','Hydrabad')
employee_details

employee_details['TC10022']['Name'].upper()

employee_details['TC10022']['Name'] = employee_details['TC10022']['Name'].upper()
employee_details

student_marks = {"001":{'phy':92,
                        'chem':97,
                        'Bio':94,
                        'Eng':96,
                        'Maths':98}}
student_marks

# fromkeys()
# dict.fromkeys(sequence,[val])

marks = dict.fromkeys(['Phy','Chem','Maths','Bio','Eng'])
marks

marks = dict.fromkeys(['Phy','Chem','Maths','Bio','Eng'],100)
marks

list1 = ['Phy','Chem','Maths','Bio','Eng']
marks = dict.fromkeys(list1,100)
marks

list1 = ['Phy','Chem','Maths','Bio','Eng']
result = {}
for sub in list1:
  result.update({sub:100})
  print(result)

list1 = ['Phy','Chem','Maths','Bio','Eng']
result = {}
for sub in list1:
  result.update({sub:100})
print(result)

city_name = ['pune','mumbai','channai','delhi']
d1 = dict.fromkeys(city_name,32)
d1

city_name = ['pune','mumbai','channai','delhi']
d1 = dict.fromkeys(city_name,32)
d1.update({'mumbai':50})
d1

string = "python"
d1 = dict.fromkeys(string)
d1

string = "python"
d1 = dict.fromkeys(string,100)
d1

string = "python"
dict.fromkeys(string,'Data science')

result = {}
for i in range(65,91):
  result.update({chr(i):i})
print(result)

dict1 = {}
for i in range(65,91):
  dict1[chr(i)]=i
print(dict1)

dict1 = {}
for i in range(65,75):
  dict1[chr(i)]=i
  print(dict1)

# cubes
cubes={}
for i in range(1,11):
  cubes.update({i:i**3})
  print(cubes)

string = """ Machine learning is a subfield of artificial intelligence,
which is broadly defined as the capability of a machine to imitate intelligent human behavior.
Artificial intelligence systems are used to perform complex tasks in a way that is similar to
how humans solve problems."""
string_list = string.split()
print(string_list)

len(string_list)

string_list.count('to')

string = """We are learning python and Data science, Python is programming language
which is used in machine learning and deep learning"""

string_list = string.split()
for i in string_list:
  count = string_list.count(i)
  print(i,count)

string = """We are learning python and Data science, Python is programming language
which is used in machine learning and deep learning"""

string_list = string.split()
word_count = {}
for i in string_list:
  count = string_list.count(i)
  word_count.update({i:count})
word_count

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
sub_marks

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
sub_marks.keys()

# Sorted dictionary by using keys

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
sorted(sub_marks.keys())

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
for sub in sorted(sub_marks.keys()):
  print(sub)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
result = {}
for sub in sub_marks:
  result.update({sub:100})
  print(result)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
result = {}
for sub in sub_marks:
  result.update({sub:100})
print(result)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
result = {}
for sub in sorted(sub_marks.keys()):
  result.update({sub:sub_marks[sub]})
  print(result)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
result = {}
for sub in sorted(sub_marks.keys()):
  result.update({sub:sub_marks[sub]})
print(result)

# sorted dictionary by using values

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':82,'maths':83}
for marks in sorted(sub_marks.values()):
  print(marks)

#values to be sorted but keys can not be sorted
sub_marks = {'phy':93,'chem':88,'bio':95,'eng':69,'maths':78}

for marks in sorted(sub_marks.values()):
  print("Marks",marks)
  for sub in sub_marks:
    print("Subject Name",sub)

# sorted subject with the help of sorted marks

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':69,'maths':78}

for marks in sorted(sub_marks.values()):
  for sub in sub_marks:
    if marks == sub_marks[sub]:
      print("Subject Name:",sub)
  print("*"*40)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':69,'maths':78}

for marks in sorted(sub_marks.values()):
  for sub in sub_marks:
    if marks == sub_marks[sub]:
      print("Subject Name:",sub)
      break
  print("*"*40)

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':69,'maths':78}
result = {}
for marks in sorted(sub_marks.values()):
  for sub in sub_marks:
    if marks == sub_marks[sub]:
      print("Subject Name:",sub)
      result.update({sub:marks})
  print("*"*40)
result

sub_marks = {'phy':93,'chem':88,'bio':95,'eng':69,'maths':78}
result = {}
for marks in sorted(sub_marks.values()):
  for sub in sub_marks:
    if marks == sub_marks[sub]:
      result.update({sub:marks})
      print(result)
      break
result

# Dict comprehension

# new_dict = {key:value for key,value in dict1}
# new_list = [value for value in sequence]

list1 = [4,5,6,7,8]
new_list = [i**3 for i in list1]
new_list

new_list = [i**3 for i in [4,5,6,7,8]]
new_list

cube = {i:i**3 for i in range(1,11)}
cube

square = {i:i**2 for i in range(1,31)}
square

# square of even numbers between 1 to 30

square = {i: i**2 for i in range(1,31) if i%2==0}
square

# The get() method returns the value of the item with the specified key.

dict1 = {'rohit':24,'monalisa':42,'sarthak':32,'sonali':45,'Atharva':37}
x = dict1.get("sonali")
x









# Datatypes Revision

# int
# float
# complex
# str
# list
# tuple
# set
# frozenset
# dict

#List

# Mutable:changable
# ordered datatype
# duplicate items are allowed
# Enclosed in []
# list items are comma seperated
# Initialized with [] or list()


# List function
# append
# extend
# insert
# remove  >> It is used to remove perticular item by using value
# pop     >> It is used to remove perticular item by using item index
# clear
# index
# count
# copy
# sort
# reverse

# Built in function
# sorted
# reversed
# min
# max
# sum

#Tuple

# Immutable: we can not modify it
# Ordered
# Duplicate items are allowed
# Enclosed in ()
# tuple items are comma seperated
# Initialized with ()


# Tuple function
# index
# count

# Built in function
# sorted
# reversed
# min
# max
# sum

# Set

# Mutable >> Changable
# Unordered Datatype >>  we can not use indexing and slicing
# Duplicates items are not allowed
# we can only add immutables items
# Enclosed in {}
# Initialize with set()
# set items are comma seperated


# Set function

# add()
# update()
# union()

# remove()
# discard()
# pop()
# clear()

# intersection()
# intersection_update()
# difference()
# difference_update()
# symmetric_difference()
# symmetric_difference_update()

# issuperset()
# issubset()
# isdisjoint()

# frozenset()

# Immutable >> we can not update frozenset
# Unordered
# Duplicates items are not allowed
# we can add only immutable items

# union
# intersection()
# difference
# symmetric_difference

# issuperset()
# issubset()
# isdisjoint()

# Dict
# Mutable
# Ordered(python >=3.7)
# Duplicates keys are not allowed, values can be duplicates
# Enclosed in {}
# Initialized with {} or dict()
# Indexing and slicing is not allowed
# keys: Immutable Datatype
# values:Any Datatypes

#Dict Function
# get
# keys
# values
# item
# update
# pop
# popitem >> It will delete last inserted Item
# clear
# fromkeys()
# setdefault
# copy()

list1 = []
bool(list1)

list1 = [5,6,7,8,9]
bool(list1)

list1 = [5,6,7,8,9]
if 10 in list1:
  print("Item is present")
else:
  print("Item is not present")

dict1 = {5:25,10:100}
if bool(dict1):
  print("Dictionary is not empty")

set1 = {}
if bool(set1):
  print("Dictionary is not empty")
else:
  print("set is empty")

set1 = {3,4,5}
if bool(set1):
  print("set is not empty")
else:
  print("set is empty")

string = "python"
bool(string)

string = ""
bool(string)

