# -*- coding: utf-8 -*-
"""Vel_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewBHDVUTLOBIp-ieqwZ8nb5Hnbaij9JM
"""

# List

# Mutable(changable)
# Duplicates are allowed
# Ordered Datatype
# enclosed by []
# comma seperated
# List is Collection of items
# we can add any datatype in list
# data type: int,float,complex,str,list,tuple,dict,set,frozenset,numpy array, pandas dataframe, pandas series


# Properties of list datatype

# List is mutable(changable) >> (add,delete,update)
# It is an ordered data type
# Duplicate items are allowed
# List are enclosed by []
# List items are comma seperate

# List Function

# 1.append()
# 2.extend()
# 3.insert()
# 4.remove()
# 5.pop()
# 6.clear()
# 7.index()
# 8.count()
# 9.copy()
# 10.sort()
# 11.reverse()


# Build in Function:
# 1.sorted()
# 2.reversed()
# 3.min()
# 4.max()
# 5.sum()

list1 = [10,20,30,40,50]
list1

list1 = [20,30,40,5,4,2,8,9,6,6,7,5,6]
print(list1)
len(list1)

set1 = {20,30,4,5,6,9}
set1

string = 'python'
len(string)

list1 = ['python','data','science']
len(list1)

# List is collection of heterogenous datatype
list1 = ['python',10,4,8,23,4.35,2,7,6.35,4+8j,'science',[4,7,9]]
list1

list1 = ['python',10,4,8,23,4.35,2,7,6.35,4+8j,'science',[4,7,9],(8,9,10)]
list1

# Accessing items in the list/ indexing
list1 = [3,4,5,6,7]
list1[0]
list1[1]
list1[2]
list1[3]
list1[4]

# Slicing
# [start_index(include): end_index(exclude) : [step_size]]
# start_index >> default value is 0
# end_index  >> default value is len(list1)

list1 = [3,4,6,7,8,1,2,9]
list1[2:5] # 2,3,4

list1 = [3,5,7,'a','c',4.9,'python']
list1[:]

list1 = [3,5,7,'a','c',4.9,'python']
list1[3:]

list1 = [3,5,7,'a','c',4.9,'python']
list1[3:6]

list1 = [3,5,7,'a','c',4.9,'python']
list1[-5:]

list1 = [3,5,7,'a','c',4.9,'python']
list1[-3:]

list1 = [3,5,7,'a','c',4.9,'python']
list1[-3:-1]

list1 = [3,5,7,'a','c',4.9,'python']
list1[2:5]

list1=[10,20,30,40,50,60,70]
print(list1[1:4])
print(list1[-6:-3])
print(list1[1:-3])
print(list1[-6:4])

# list will be reversed

list1 = [10,20,30,40,50,60,70]
list1[::-1]

list1 = [10,20,30,40,50,60,70]
list1[1:5:2]

list1 = [10,20,30,40,50,60,70]
list1[1:6:2]

list1 = [10,20,30,40,50,60,70]
list1[0:7:3]

list1 = [10,20,30,40,50,60,70]
list1[-2:-5]

list1 = [10,20,30,40,50,60,70]
list1[-2:-5:-1]

# Access items by using for loop

# sequence  >> list

# for variable in sequence:
#   statement1
#   statement2
#   statement3

list1 = [5,6,7,8,9]
for i in list1:
  print(i)

list1 = [5,6,7,8,9]
for i in list1:
  print(i**2)

list1 = [5,6,7,8,9]
for i in list1:
  print("Hello python")

city_name = ['pune','mumbai','delhi','chennai','Bangalore']
for city in city_name:
  print(city)

list2 = [1,2,3,4,5]
for val in list2:
  print("Item is:",val)

city_name = ['pune','mumbai','delhi','chennai','Bangalore']
for city in city_name:
  print("city name is:",city)

city_name = ['pune','mumbai','delhi','chennai','Bangalore']
for city in city_name:
  city = city.upper()
  print("City name is:",city)

city_name = ['pune','mumbai','delhi','chennai','Bangalore']
index = 0
for city in city_name:
  print(f"city name at index {index} is {city.upper()}")
  print("*"*40)
  index+=1

city_name = ['pune','mumbai','solapur','barshi','jamgaon']
index=0
for city in city_name:
  print(f"city name is at index {index} is {city.upper()}")
  index +=1

# enumerate()

city_name = ['pune','mumbai','solapur','barshi','jamgaon']
index = 0
for index,val in enumerate(city_name):
  print(f"City name at index {index} is {val.upper()}")
  index+=1

#range()

a = range(5)
print(type(a))

for i in range(2,7):
  print(i)

for i in range(10,21):
  print(i)

# print even numbers between 0-30
list(range(0,31,2))

# print odd numbers between 0-30
list(range(1,30,2))

list(range(3,31,3))

list(range(5,51,5))

a = 5
for i in range(a,a*10+1,a):
  print(i)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
for i in range(len(city_name)):
  print(i,city_name)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
for i in range(len(city_name)):
  print(i,city_name[i])

city_name = ['pune','mumbai','delhi','bangalore','chennai']
for i in range(len(city_name)):
  print(i,city_name[i].upper())

list(range(5,1,-1))

list(range(-5,6))

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name[::-1]

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name[4:1:-1]

a = [11,12,13,14,15,16,17,18,19,20]
for i in a:
  print(i**2)

num = []
for i in range(0,200):
  num.append(i**2)
num

a = ['phy','Chem','MATHS','Bio','ENg']
new_list = []
for i in a:
  new_list.append(i.title())
new_list

# append()

# list.append(value)
# List will get update itself
# It is used to add the items at last index

list1 = [4,5,6,7,8]
list1.append(1000)
list1

list1 = [4,5,6,7,8]
list1.append(1000)
list1.append(2000)
list1

list1 = [4,5,6,7,8]
list1.append('python')
list1

city_name = ['Pune','Mumbai','Channai','Delhi']
city_name

city_name = ['Pune','Mumbai','Channai','Delhi']
city_name.append('Bengalore')
city_name

sub_name = ['Phy','Chem','Maths']
sub_name.append('Eng')
sub_name.append('Bio')
sub_name

list1 = [4,5,7,8,9]
squares = []

squares.append(16)
squares.append(25)
squares.append(49)
squares.append(64)
squares.append(81)
squares

list1 = [4,5,7,8,9]
squares = []
for i in list1:
  print(i**2)
  squares.append(i**2)
squares

list1 = [4,5,7,8,9]
squares = []
for i in list1:
  squares.append(i**2)
  print(squares)

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
list1.append(list2)
list1

# extend()

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
list1.extend(list2)
list1

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
list1.extend(list2)
print("list1",list1)
print("list2",list2)

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
list2.extend(list1)
print("list1",list1)
print("list2",list2)

list1 = [2,3,4,5,6]
tuple1 = (8,9,10,11)
list1.extend(tuple1)
list1

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
for i in list2:
  list1.append(i)
  print(list1)

list1 = [2,3,4,5,6]
list2 = [10,11,12,13,14]
for i in list2:
  list1.append(i)
print(list1)

# insert()
# list1.insert(index,value)

list1 = [3,4,5,6,8,9]
list1.insert(4,7)
list1

list1 = [10,20,40,50,60]
list1.insert(2,30)
list1

list1 = [10,20,40,50,60]
list1.insert(7,70)
list1

list1 = [10,20,40,50,60]
list1.insert(2,'python')
list1

# Delete items from list

# remove   list1.remove(value)
# pop
# clear

# del keyword

list1 = [10,20,40,50,60]
list1.remove(50)
list1

list1 = [10,20,40,50,60]
list1.remove(60)
list1

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.remove('delhi')
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city = 'delhi'

if city in city_name:
  city_name.remove(city)
  print(f"{city} is deleted from list")
else:
  print(f"{city} is not present in given list")

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city = 'Delhi'

if city in city_name:
  city_name.remove(city)
  print(f"{city} is deleted from list")
else:
  print(f"{city} is not present in given list")

# pop()
# list.pop(index)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.pop(2)
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.pop(3)
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.pop(2)  #  ['pune','mumbai','bangalore','chennai']
city_name.pop(2) #  ['pune','mumbai','chennai']
city_name

# clear()
# list.clear()

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.clear()
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
print(city_name)
del city_name

string = "data science"
print(string)
del string

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name[1]

city_name = ['pune','mumbai','delhi','bangalore','chennai']
del city_name[1]
print(city_name)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
del city_name[1]  # ['pune','delhi','bangalore','chennai']
del city_name[1]  # ['pune','bangalore','chennai']
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name[0] = 'kolkata'
city_name[-1] = 'pune'
city_name

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name[0],city_name[-1] = city_name[-1],city_name[0]
city_name

list1 = [10,20,30,40,50]
list1[0] = list1[-1]
list1[-1] = 10
list1

# index()
# ind = list.index(item)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city_name.index('bangalore')

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city = 'mumbai'
city_name.index(city)

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city = 'mumbai'
if city in city_name:
  index = city_name.index(city)
  print(f"index of {city} is {index}")
else:
  print(f"{city} is not present in list")

city_name = ['pune','mumbai','delhi','bangalore','chennai']
city = 'Mumbai'
if city in city_name:
  index = city_name.index(city)
  print(f"index of {city} is {index}")
else:
  print(f"{city} is not present in list")

city_name =  ['pune','mumbai','delhi','chennai','bangalore','mumbai','chennai','pune','bangalore']
for index,city in enumerate(city_name):
  print(index,city)

city_name =  ['pune','mumbai','delhi','chennai','bangalore','mumbai','chennai','pune','bangalore','mumbai']
index_list = []
for index,city in enumerate(city_name):
  if city == 'mumbai':
    print(index,city)
    index_list.append(index)
index_list

# copy()
list1 = [3,5,6,8,9]
list2 = list1
print("List1",list1)
print("List2",list2)

list1 = [3,5,6,8,9]
list2 = list1
list1.append(1000)

print("List1",list1)
print("List2",list2)

list1 = [3,5,6,8,9]
list2 = list1.copy()   # shallow copy
list1[2]  = 'python'

print("List1",list1)
print("List2",list2)

# Nested list
# list in list

list1 = [[2,3,4],[5,6,7],[8,9,10],[11,12,13]]
len(list1)

list1 = [[2,3,4],[5,6,7],[8,9,10],[11,12,13],14,15,16,17]
len(list1)

list1 = [[2,3,4],[5,6,7],[8,9,10],[11,12,13],14,15,16,17]
list1[2][0]

list1 = [[2,3,4],[5,6,7],[8,9,10],[11,12,13],14,15,16,17]
list1[-3]

# Shallow copy

list1 = [1,2,3,[4,5],6,7]
list2 = list1.copy()  # Shallow copy
list1[3][0] = 4000

print("List1",list1)
print("List2",list2)

# deepcopy()

import copy
list1 = [1,2,3,[4,5],6,7]
list2 = copy.deepcopy(list1)
list1[3][0] = 4000

print("List1",list1)
print("List2",list2)

# deepcopy()

import copy
list1 = [1,2,3,[4,5],6,7]
list2 = copy.deepcopy(list1)
list2[4] = 6000

print("List1",list1)
print("List2",list2)

# sort()
# list.sort()

list1 = [6,8,9,2,4,1,5,3,7]
list1.sort()
list1

# Ascending Order
list1 = [6,8,9,2,4,1,5,3,7]
list1.sort(reverse = False)
list1

# Descending Order
list1 = [6,8,9,2,4,1,5,3,7]
list1.sort(reverse = True)
list1

sub_name = ['Phy','Chem','Maths','Eng','Bio']
sub_name.sort()
sub_name

sub_name = ['Phy','Chem','Maths','Eng','Bio']
sub_name.sort(reverse = True)
sub_name

sub_name = ['Phy','chem','maths','Eng','Bio']
sub_name.sort()
sub_name

sub_name = ['Phy','chem','maths','Eng','Bio']
sub_name.sort(reverse = False)
sub_name

sub_name = ['Phy','chem','maths','Eng','Bio']
sub_name.sort(reverse = True)
sub_name

# reverse()
# lis1.reverse()

list1 = [6,8,9,2,4,1,5,3,7]
list1.reverse()
list1

list1 = [6,8,9,2,4,1,5,3,7]
list1 = list1[::-1]
list1

sub_name = ['Phy','chem','maths','Eng','Bio',80,90]
sub_name.reverse()
sub_name

sub_name = ['Phy','chem','maths','Eng','Bio',80,90]
sub_name = sub_name[::-1]
sub_name

# sorted

list1 = [6,8,9,2,4,1,5,3,7]
list1.sort()
list1

list1 = [60,80,90,20,40,10,50,30,70]
new_list = sorted(list1)

print("List1",list1)
print("New list",new_list)

list1 = [60,80,90,20,40,10,50,30,70]
new_list = sorted(list1,reverse=False)

print("List1",list1)
print("New list",new_list)

list1 = [60,80,90,20,40,10,50,30,70]
new_list = sorted(list1,reverse=True)

print("List1",list1)
print("New list",new_list)

#reversed()

list1 = [60,80,90,20,40,10,50,30,70]
list1.reverse()
list1

list1 = [60,80,90,20,40,10,50,30,70]
reversed_list = list(reversed(list1))
reversed_list

# max()

list1 = [60,80,90,20,40,10,50,30,70]
max(list1)

# min()

list1 = [60,80,90,20,40,10,50,30,70]
min(list1)

# sum()

list1 = [60,80,90,20,40,10,50,30,70]
sum(list1)

list1 = [4,5,2,7,8.3,'Python',[9,10,11]]
list1[-1][0]

list1 = [[1,2,3],[10,20,30],[40,50,60],[7,8,9]]  # [1,2,3,10,20,30,40,50,60,7,8,9]
list2 = []
for i in list1:
  for j in i:
     list2.append(j)
list2

# list
# mutable: changable
# duplicates allowed
# ordered datatype
# enclosed in []
# items are comma seperated
# we can add any datatype in the list (int,float,complex,list,tuple,dict,set)

# functions

# append()
# extend()
# insert()
# remove()
# pop()
# clear()
# index()
# count()
# copy()
# sort()
# reverse()

# min()
# max()
# sum()
# sorted()
# reversed()

a = [1,2,3,5,6,7]
a.append(9)
a

a = [1,2,3,5,6,7]
a.append([10,20,30])   # append will add only 1 item at last index
a

a = [1,2,3,5,6,7]
b = [10,20,30,40]
a.extend(b)         # extend will extend the given list
a

a = [1,2,3,5,6,7]   #insert will add item at specific index
a.insert(2,10)
a

a = [1,2,3,5,6,7]
a.insert(0,'python')
a

a = [1,2,3,5,'Python',9,6,7,'data'] # remove will remove specific item
a.remove(7)
a

a = [1,2,3,5,'Python',9,6,7,'data']
a.remove('data')
a

a = [1,2,3,5,'Python',9,6,7,'data']
a.pop(4)
a

a = [1,2,3,5,'Python',9,6,7,'data']
a.pop(3)
a

a = [1,2,3,5,'Python',9,6,7,'data']
a.clear()           #delete whole list
a

a = [1,2,3,5,'Python',9,6,7,'data']
b = a.index(5)
b

a = [1,2,3,5,'Python',9,6,7,'data']
b = a.index('Python')
b

a = [1,2,3,5,'Python',9,6,7,'data']
b = a.index('data')
b

a = [1,2,'data',3,5,'Python',9,6,3,7,'data',3]
b = a.count('data')
b

a = [1,2,'data',3,5,'Python',9,6,3,7,'data',3]
b = a.count(3)
b

a = [1,2,'data',3,5,'Python',9,6,3,7,'data',3]
b = a.copy()
print(a)
print(b)

a = [1,2,3,5,9,6,3,7,3]
a.sort()
a

a = ['python','data','machine','deep','learn','grow']
a.sort()
a

a = ['python','data','machine','deep','learn','grow']
a.reverse()
a

a = [1,2,3,5,9,6,3,7,3]
min(a)

a = [1,2,3,5,9,6,3,7,3]
max(a)

a = [1,2,3,5,9,6,3,7,3]
sum(a)

a = [1,2,3,5,9,6,3,7,3]
sorted(a)

a = [1,2,3,5,9,6,3,7,3]
b = list(reversed(a))
b

