# -*- coding: utf-8 -*-
"""OOPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sq8-zL-E9J21qb48maZUKaNPeN-m8AR4
"""

#class
#object
# __init__()
#Inheritance


#Encapsulations
#Polymorphisms
#Iterators
#Generators
#Decorators

#Inheritance
#single inheritance
#multiple inheritance
#multilevel inheritance
#heirarchical inheritance
#hybrid inheritance

#single inheritance

class Parent():
  def __init__(self):
    self.new = "Pretty"  # Instance variable
    print("New:",self.new)
    print("We are in INIT method of Parent Class")

  def Teaching(self,x,y):
    self.x = 10
    self.y = "JAVA"
    print("X:",self.x)
    print("Y:",self.y)
    print("We are in Teaching method of Parent Class")


class Child(Parent):
  def __init__(self):
    print("We are in INIT method of Child Class")

  def Working(self,x,y):
    self.x = 100
    self.y = "python"
    print("X:",self.x)
    print("Y:",self.y)
    print("We are in Working method of Child Class")

x1 = Parent()
x1.Teaching(40,50)

#multiple inheritance

class Father():
  x = "PYTHON"  # calss variable
  def __init__(self):  # Execute automatically
    self.x = 10   # Instance variable
    print("X:",self.x)
    print("We are in INIT method of Father Class")

  def Farming(self,x,y):
    print("Farming Method")
    self.x = 10
    self.y = "Mango"

class Mother():
  def __init__(self):
    print("We are in INIT method of Mother Class")

class Child(Father,Mother):
  def __init__(self):
    print("We are in INIT method of Child Class")
    Father.__init__(self)
    Mother.__init__(self)  # calling INIT method of Parent class From Child Class

  def Farming1(self,x,y):
    print("Farming Method")
    self.x = 10
    self.y = "Mango"

c1 = Child()
c1.Farming1

#multilevel inheritance

new = "YULULU"  #  Global var
class GrandFather():
  x = 1009900   # class variable
  def __init__(self):
    self.x = "JAVA"
    self.y = 1000  # Instance variable
    print("We are in INIT method of GrandFather Class")

  def Gardning(self):
    x = "Python"  # local var
    print("GrandFather loves gardening")

class Father(GrandFather):
  def __init__(self):
    print("We are in INIT method of Father Class")

  def Farming(self):
    print("Father loves Farming")

class Child(Father):
  def __init__(self):
    print("We are in INIT method of Child Class")
    Father.__init__(self)
    GrandFather.__init__(self)   # calling INIT method of Parent class From Child Class

  def Playing(self):
    print("Child loves Playing")


c1 = Child()  # Object of child class
c1.Playing()

#heirarchical inheritance

class Parent():
  pass
class Child1(Parent):
  pass
class Child2(Parent):
  pass

# Hybrid inheritance

class Parent():
  pass
class Child1(Parent):
  pass
class Child2(Parent):
  pass
class Child3(Child1,Child2):
  pass

# Encapsulations


class Parent():
  company = "TCS"  # Public class var
  __id = 100      # Private class var
  def __init__(self,x,y):
    print("We are in INIT METHOD OF Parent class")
    self.x = "JAVA"
    self.y = 100000
    self.__salary = 90000000  # Private instance variable
    self.name = "Aishwarya"  # Public instance variable
    self.__age = 25  # Private instance variable
    print("X:",self.x)
    print("Y:",self.y)

  def Employeeinfo(self):
   print("Name:",self.name)
   print("Company:",self.company)
   print("Salary:",self.__salary)
   print("Age:",self.__age)

class Child(Parent):
  def __init__(self):
    print("We are in INIT METHOD OF Child class")

  def Employeeinfo(self):
    print("We are in Employeeinfo Function")
    print("Company:",self.company)
    # print("Salary:",self.__salary)  # will get AttributeError
    # we can not access Public/Private instance variable in other class


c1 = Child()
c1.Employeeinfo()

#Polymorphisms

class Reactangle():
  def area(self,l,b):
    self.l=10
    self.b=20
    print(f"Area of Reactangle:{l*b}",)
class Square():
  def area(self,side):
    self.side=100
    print(f"Area of Square:{side*side}",)
class Circle():
  def area(self,r):
    pi = 3.14
    self.r=100
    print(f"Area of Circle:{pi*(self.r),(self.r)}")

c1 = Square()
c1.area(10)

# Polymorphisms means same func name used in diff classes with diff functionality

# Iterators

x = [2,3,4,5,6,7]
obj = iter(x)
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))

# Iterators

x = [2,3,4,5,6,7,8]
obj = iter(x)
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))

# Iterators


class Accessitems():

  def __iter__(self):
    print("Its an iterator method")
    self.a = 10
    return self
  def __next__(self):
    print("Its an next method")
    print("self.a:",self.a)
    return 10000

obj =  Accessitems()
my_iter = iter(obj)
print(next(my_iter))

#Generators

list1 = [2,3,4,5,6,7,8,9]
def even_list():
  for i in list1:
    if i%2==0:
      yield i    # yield statement mostly is in the loop

even_list()
for x in even_list():
  print(x)

#Decorators

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")

  innerfunction()

  print("End of outer function")
  return 1000

outerfunction()

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")

  innerfunction()

  # print("End of outer function")
  # return 1000

x = outerfunction()

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")  # Local function

  return innerfunction



x = outerfunction()

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")  # Local function

  return innerfunction() # This is incorrect method we can not call func in return statement

x = outerfunction()

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")  # Local function

  return innerfunction

x = outerfunction()
x()

def outerfunction():
  print("We are in Outer Function")

  def innerfunction():
    print("We are in Inner Function")  # Local function

  return innerfunction

x = outerfunction()()

def outerfunction(a=10):
  print("We are in Outer Function")
  print("A:",a)
  print("*"*30)

  def innerfunction(b):
    print("We are in Inner Function")  # Local function
    print("B:",b)

  return innerfunction

x = outerfunction()
x(30)

def outerfunction(a=10):
  print("We are in Outer Function")
  print("A:",a)
  print("*"*30)

  def innerfunction(b):
    print("We are in Inner Function")  # Local function
    print("B:",b)

  return innerfunction  # return object of INNER Function

def my_func():
  print("We are in my function")

my_func()
outerfunction()

def outerfunction(func):
  print("We are in Outer Function")

  def innerfunction(b):
    print("We are in Inner Function")  # Local function
    print("B:",b)

  return innerfunction  # return object of INNER Function

def my_func():
  print("We are in my function")

outerfunction(my_func)

def outerfunction(func):
  print("We are in Outer Function")

  def innerfunction(b):
    print("We are in Inner Function")  # Local function
    print("B:",b)


  return innerfunction  # return object of INNER Function

def my_func():
  print("We are in my function")

x = outerfunction(my_func)
x(10)

def outerfunction(func):  # Higher Order Function
  print("We are in Outer Function")

  def innerfunction(b):   # Local Function
    print("We are in Inner Function")  # Local function
    print("B:",b)
    func()


  return innerfunction

def my_func():
  print("We are in my function")

x = outerfunction(my_func)
x(10)

def outerfunction(func):  # Higher Order Function
  print("We are in Outer Function")

  def innerfunction():   # Local Function
    print("We are in Inner Function")  # Local function
    print("*"*20)
    func()
    print("$"*20)


  return innerfunction

@outerfunction   # Decorator
def my_func():
  print("We are in my function")

my_func()

# decorators

def outerfunc(func):
  print("We are in Outer Func")

  def innerfunc():
    print("We are in Inner func")
    print("*"*20)
    func()
    print("#"*20)

  return innerfunc


@outerfunc  # Decorator
def my_func():
  print("We are in my func")


my_func()

