# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFLoyGWXN7DScCeqkFExlqidD_HtOYI5
"""

# String,Indexing and Slicing

# string are immutables
# String is collection of characters surrounded by either single quotes,double quotes,triple quotes(triple single quotes, triple double quotes)
# Characters can be digits(0-9),spaces,alphabates,special characters(@,#,$,%,!)

# we cannot use single quotes in single quotes
# we cannot use double quotes in double quotes
# we cannot use tripal quotes in tripal quotes

str1 = "Python and Data science $"
print(str1)
type(str1)

s1 = 'python'
s2 = "python"
s3 = '''python'''
s4 = """python"""
print(s1)
print(s2)
print(s3)
print(s4)

str = 'python and "Data" Science'
str

str = "python and 'Data' Science"
str

text = "Machine learning is a branch of artificial intelligence (AI) and computer science which focuses on the use of data and algorithms to imitate the way that humans learn, gradually improving its accuracy. IBM has a rich history with machine learning."
text

text = """Machine learning is a branch of artificial intelligence (AI) and computer science
which focuses on the use of data and algorithms to imitate the way that humans learn,
gradually improving its accuracy. IBM has a rich history with machine learning."""

text

s1 = "23445346"
s1

str2 = "Aishwarya"
len(str2)

s1 = "python's"
len(s1)

# Escape Characters

s1 = "Python and \"Data\" Science"
s1

# \n is used for new line

a = "python and \n machine learning"
print(a)

# r means rowstring (It will not consider escape characters)
x = r"C:\Users\HP ECS\Documents\ \n vscodeall\css"
print(x)

x = r"C:\Users\HP ECS\Downloads\github\nphpmailer\src"
print(x)

# \t used to add space

a = "python an \t d data science"
print(a)

# String indexing and Slicing
# Indexing will always start from 0

str = "Python"
length = len(str)
length

str[3]

# If we want to fetch the last variable of the string
str[length-1]

# Negative Indexing

x = "Data science"
x[-1]

a = "aishu"
a[-1]

# String Slicing
# string[start index : end index]  ---------- (Strat index >> Include ,   end index >> Exclude)
# Default start index >> 0
# Default end index >> len(string)

string = "Aishwarya"
string[0:4]

text = "machine learning"
len(text)
text[2:7]

text = "machine"
len(text)
text[0:7]

text[0:len(text)]

text[0:]

text[:]

text[3:]

text[:3]

# Strings are immutable
# immutable means we cannot modify string

str = "python"
str[0]

str = "python"
str[0]

str = " python "
len(str)

text = "Aishwarya"
text[::2]

text = "Aishwarya"
text[1::2]

# string             =   p  y  t  h  o  n
# positive indexing  =   0  1  2  3  4  5
# negative indexing  =  -6 -5 -4 -3 -2 -1

text = "python"
text[2:5]

text = "python"
text[-4:-1]

text = "python"
text[2:-1]

text = "Machine learning"
text[-10:]

text = "python"
text[0::2]

text = "python"
text[5:2:-1]

text = "python"
text[5:1:-2]

text = "python"
text[5:1:-1]

# String Function

s1 = "python"
print(s1[2:5])
print(s1)

s1 = "python"
s2 = s1[2:5]
print(s1)
print(s2)

a = 10
b = a+10
print(a)
print(b)

a=10
print(a)

a = a +20
print(a)

# String function


# capitalize()
# upper()
# lower()
# title()
# swapcase()
# casefold()
# lstrip()
# rstrip()
# strip()
# replace()
# count()
# index()
# find()
# split()
# join()
# endswith()
# startswith()
# isalpha()
# isdecimal()
# isdigit()
# isnumeric()
# islower()
# isupper()
# istitle()
# isspace()
# zfill()
# center()

# capitalize() it will capitalize only 1st character of string and all remaining are in lower case

string = "data science"
string.capitalize()

string = "DATA SCIENCE"
string.capitalize()

string = "DATA SCIENCE"
s2 = string.capitalize()
print(string)
print(s2)

# upper() It will convert all characters in upper case
string = "python"
string.upper()

a = "Data Science"
a.upper()

# lower() It will convert all characters in lower case
a = "AISHWARYA"
a.lower()

a = "PYThon"
a.lower()

# title

x = "machine learning"
x.title()

a = "united state of america"
a.title()

a = "united state of america"
a.capitalize()

string = "python and data science"
# string.capitalize()
string.title()

str1 = "python"
str2 = "python"
str1 == str2

str1 = "python"
str2 = 'Python'
str1 == str2

str1 = "PYTHON"
str2 = "PYTHON"
if str1 == str2:
  print(" Two string are equal ")

adhar_name = "aishwarya satpute"
pancard_name = "AISHWARYA_SATPUTE"

adhar_name == pancard_name

if adhar_name == pancard_name:
  print("Both names are same")
else:
  print("Both names are not same")

adhar_name = "aishwarya satpute"
pancard_name = "AISHWARYA SATPUTE"

print(adhar_name.title())
print(pancard_name.lower())

if adhar_name == pancard_name:
   print("both name are same")
else:
   print("Both names are different")
   print("hello")

#swapcase
# It inverts the case of characters
# upper case >> lower
# lower case >> upper

string = "Aishwarya"
string.swapcase()

# lstrip (It remove all leading white spaces)

str1 = "           python"
str1.lstrip()

# rstrip (It remove all trailing white spaces)

str1 = "Aishwarya    "
str1.rstrip()

str1 = "           Aishwarya              "
str1 = str1.lstrip()
str1 = str1.rstrip()
str1

str1 = "           Aishwarya              "
str1 = str1.lstrip().rstrip()
str1

str1 = "           Aishwarya              "
str1 = str1.lstrip().rstrip().upper()
str1

# strip()  = lstrip + rstrip

str1 = "         Aishwarya                "
str1.strip()

# casefold()

str1 = "Data Science"
str1.lower()

str1 ="Data Science"
str1.casefold()

str1 = "If you don't have ß"
str1.casefold()

# replace()
# string.replace(old_substring, new_substring,[count])
# substring = single character, word, whole string

str1 = ("Python and Data science")
str1.replace("Python", "Java")    # hear python is replaced with java

str1 = ("Python and Data science")
str1.replace("a", "A")

string = "python and data science"
string.replace("a","*")

str1 = ("Python and Data science")
str1.replace(" ", "+")

str1 = ("Python and Data science")
str1.replace("a", "*")

# Remove all the vowels from given string
str1 = ("Python and Data science")
str1.replace("a","*") .replace("e","*").replace("i","*").replace("o","*").replace("u","*")

string = "python, data science, Machine learning, Deep learning "
string.replace("a","*").replace("e","*").replace("i","*").replace("o","*").replace("u","*")

# count

a = "Python and Data Science"
a.count("a")

a = "Python and Data Science, Python and ML"
a.count("Python")

a = "Python and Data Science"
a.count("DATA")

a = "Python and Data Science, Python and ML"
a.count(" ")

a = "Python and Data Science, Python and ML"
a.count("P",0,30)

a = "Python and Data Science, Python and ML"
a.count("P",0,10)

a = "Python and Data Science, Python and ML"
a[10:20]
a.count("P",0,10)

string = "Python and Data Science, Python and ML"
substring = "Python"
a.count(substring)

string = "Python and Data Science, python and ML"
substring = "python"
string.count(substring)

string = "Python and Data Science, python and ML"
substring = "python"
string2 = string.lower()
string2.count(substring)

string = "      Python and Data Science, python and ML      "
string.lstrip().rstrip().count("Python")

# index()
# string.index(substring, [start_index],[end_index])

string = "Machine learning and Deep learning"
string.index("l")

string = "Machine learning and Deep learning"
string.index("learning")

string = "Machine learning and Deep learning"
substring = "Deep"
substring in string

string = "Machine learning and Deep learning"
substring = "deep"
substring in string

string = "Machine learning and Deep learning"
substring = "Machine"
if substring in string:
  print("substring is present in given string")
else:
  print("substring is not present in given string")

string = "python and data science"
substring = "python"
if substring in string:
  print("substring is present in given string")
else:
  print("substring is not present in given string")

string = "Machine learning and Deep learning"
substring = "machine"
if substring in string:
  print("substring is present in given string")
else:
  print("substring is not present in given string")

# If we want to print substring in output
string = "Machine learning and Deep learning"
substring = "Machine"
if substring in string:
  print(f"{substring} is present in given string")
else:
  print(f"{substring} is not present in given string")

string = "Machine learning and Deep learning"
substring = "Deep"
if substring in string:
  print(f"{substring} is present at index {index}")
  index = string.index(substring)
  print("Index is: ",index)
else:
  print(f"{substring} is not present at index {index}")

string = "Machine learning and Deep learning"
string.index('e',7,20)

# Find
# string.find(substring,[start_index],[end_index])

string = "Machine learning and Deep learning"
string.find("Deep")

string = "Machine learning and Deep learning"
string.find("deep")

string = "Machine learning and Deep learning"
string.find("python")

string = "Machine learning and Deep learning"
index = string.find("learning")
index
if index == -1:
  print("substring is not present")
else:
  print("substring is present ")

string = "Machine learning and Deep learning"
index = string.find("python")
index
if index == -1:
  print("substring is not present")
else:
  print("substring is present ")

# Split()  >>  Used to convert string to list data type

str1 =  "Machine learning and Deep learning"
str1.split()

str1 = "Machine learning is a branch of artificial intelligence (AI) and computer science which focuses on the use of data and algorithms to imitate the way that humans learn, gradually improving its accuracy. IBM has a rich history with machine learning."
str1.split()

str1 = """Machine learning (ML) is an umbrella term for solving problems for which development of algorithms by human programmers would be
cost-prohibitive, and instead the problems are solved by helping machines "discover" their "own" algorithms, without needing to be explicitly
told what to do by any human-developed algorithms. Recently, generative artificial neural networks have been able to surpass results of many
previous approaches. Machine-learning approaches have been applied to large language models, computer vision, speech recognition,
email filtering, agriculture and medicine, where it is too costly to develop algorithms to perform the needed tasks.

The mathematical foundations of ML are provided by mathematical optimization (mathematical programming) methods.
Data mining is a related (parallel) field of study, focusing on exploratory data analysis through unsupervised learning."""

list2 = str1.split(".")
print(list2[1])

folder_path = r"C:\Users\HP ECS\Documents\vscodeall\PythonProject"
folder_path.split()

folder_path = r"C:\Users\HP ECS\Documents\vscodeall\PythonProject"
folder_path.split("\\")

folder_path = r"C:\Users\HP ECS\Documents\vscodeall\PythonProject"
folder_path.split("\\")[-1]

image_file = r"C:\Users\HP ECS\Documents\vscodeall\DSPL\images_gradient_descent.png"
image_file.split("\\")[-1].split(".")[1]

str1 = """Machine learning (ML) is an umbrella term for solving problems for which development of algorithms by human programmers would be
cost-prohibitive, and instead the problems are solved by helping machines "discover" their "own" algorithms, without needing to be explicitly
told what to do by any human-developed algorithms. Recently, generative artificial neural networks have been able to surpass results of many
previous approaches. Machine-learning approaches have been applied to large language models, computer vision, speech recognition,
email filtering, agriculture and medicine, where it is too costly to develop algorithms to perform the needed tasks.

The mathematical foundations of ML are provided by mathematical optimization (mathematical programming) methods.
Data mining is a related (parallel) field of study, focusing on exploratory data analysis through unsupervised learning."""


list2 = str1.split("\n")
list2

str1 = """Machine learning (ML) is an umbrella term for solving problems for which development of algorithms"""
str1.split("for")

# join()
# substring.join(list)

list1 = ['Machine','Learning','and','Deep','Learning']
' '.join(list1)

string = ["python","and","data","science"]
' '.join(string)

list1 = ['Machine','Learning','and','Deep','Learning']
x='\n'.join(list1)
x

list1 = ['Machine','Learning','and','Deep','Learning']
'PYTHON'' '.join(list1)

a = ['aish','nicks','neha','aditya','rohan','gauri']
"#".join(a)

a = ['aish','nicks','neha','aditya','rohan','gauri']
"#"' '.join(a)

list2 = ['python','java','machinelearning','datascience']
x = "*".join(list2)
x

list1 = ['Machine','Learning','and','Deep','Learning']
'-'.join(list1)

#list
string = 'Python'
list(string)

str1 = """Machine learning (ML) is an umbrella term for solving problems for which development of algorithms"""
list(str1)

# question
string = "python"
# result = "p-y-t-h-o-n"

string = "python"
list2 = list(string)
'-'.join(list2)

a = "java"
list(a)

a = "java"
b = list(a)
'-'.join(b)

string = "java"
'-'.join(string)

# endswith()  >>  endswith()  result in true or false
string = "python"
string.endswith("n")

string = "python and data science"
string.endswith("E")

string = "python and data science"
string.endswith("e")

string = "  python and data science  "
string.endswith("e")

string = "  python and data science  "
string.endswith(" ")

string = "science"
for var_name in string:  # loop will iterate in 6 times
  # sequence  >>  str,list,tuple,set,frozenset,array,dataframe,dict etc
  print(var_name)

string = "python"
for char in string:
  print(char)
  print("hiiiii")
  print("*******************")

string = "python"
count = 0
for char in string:
  print(char)
  print(count)
  print("*******************")

string = "python"
count = 0
for char in string:
  count=count+1
  print(char)
  print(count)
  print("*******************")

string = "python"
count = 0
for char in string:
  count=count+1
  print(char)
  print(f"character at index {count} is {char}")
  print("*******************")

string = "java"
count = 0
for char in string:
  count = count+1
  print(char)
  print(f"character at index {count} is {char}")
  print("****************************")

string = "python"
for index,val in enumerate(string):
  print(index,val)

list1 = [5,2,8,4,9,42,36,34,6,1]
for items in list1:
  print(items)

#startswith()

string = "python"
string.startswith('p')

string = "python"
string.startswith('P')

string = "    python    "
string.strip().startswith('p')

# isalnum() >>  Is alpha Numeric? (Return True/False Value)
# a-z, A-Z, 0-9
# space is not allowed

string = "python"
string.isalnum()

string = "python123"
string.isalnum()

string = "Data Science"
string.isalnum()

string = "DataScience"
string.isalnum()

string = "Data-Science"
string.isalnum()

string = "7584647"
string.isalnum()

# isalpha()  >>  (a-z)(A-Z)
# True  >> If the string contains lower case(a-z) and upper case(A-Z) characters
# space is not allowed

string = "Python"
string.isalpha()

string = "PYTHON"
string.isalpha()

string = "Python3532"
string.isalpha()

# isdecimal()   >>  Return True/False
# 0-9
# True  >>  If strings contains only digits and unicode for digits(0-9)
# space is not allowed
# dot case is not allowed

string = "323424"
string.isdecimal()

string = "387 472 324"
string.isdecimal()

# Hear we remove the space b/w  numbers
string = "387 472 324"
string = string.replace(' ','')
string.isdecimal()

a = "343 473 867"
b = a.replace(" ",'')
b.isdecimal()

string = "\u0030"
string.isdecimal()

string = "\u0029"
string.isdecimal()

string = "\u0060"
string.isdecimal()

string = "\u0090"
string.isdecimal()

# isdigit()   >>  Return True/False
# 0-9
# True  >>  If strings contains only digits and unicode for digits(0-9)
# True  >>  If strings contains subscript and superscript(unicode)
# space is not allowed
# dot case is not allowed

string = "python"
string.isdigit()

string = "3242352"
string.isdigit()

string = "324 235 2"
string.isdigit()

#subscript
string = "\u2070"
string.isdecimal()

string = "\u00B3"
string.isdigit()

# isnumeric()

# isdigit()   >>  Return True/False
# 0-9
# True  >>  If strings contains only digits and unicode for digits(0-9)
# True  >>  If strings contains subscript and superscript(unicode),vulger fraction
# space is not allowed
# dot case is not allowed

string = "python"
string.isnumeric()

string = "7565"
string.isnumeric()

string = "85.974"
string.isnumeric()

string = "85-564"
string.isnumeric()

# isdecimal()   >>  0-9, unicode(0-9)
# isdigit()     >>  0-9, unicode(0-9), subscript, superscript
# isnumeric()   >>  0-9, unicode(0-9), subscript, superscript,vulgar fraction

string = "python"
print(string.isdecimal())
print(string.isdigit())
print(string.isnumeric())

string = "python1234"
print(string.isdecimal())
print(string.isdigit())
print(string.isnumeric())

string = "3498759348"
print(string.isdecimal())
print(string.isdigit())
print(string.isnumeric())

string = "349 8759 348"
print(string.isdecimal())
print(string.isdigit())
print(string.isnumeric())

# islower()
# True/False
# True  >>  If all alphabates are in lower case
# Space is allowed

string = "python"
string.islower()

string = "python and data science"
string.islower()

string = "python and data Science"
string.islower()

string = "python and data science 374637"
string.islower()

# isupper()
# True/False
# True  >>  If all alphabates are in upper case
# Space and special characters are allowed

string = "python"
string.isupper()

string = "Python"
string.isupper()

string = "PYTHON"
string.isupper()

string = "PYTHON AND DATA SCIENCE 763"
string.isupper()

# istitle()
# True/False
# True  >>  If all alphabates are in title case
# Space and special characters are allowed

string = "Python"
string.istitle()

string = "Python And Data Science "
string.istitle()

# isspace()
# True/False
# True  >> If string contain only space(one or many spaces)

string = ' '
string.isspace()

string = '     t        '
string.isspace()

text = """Data science is the study of data to extract meaningful insights for business.
It is a multidisciplinary approach that combines principles and practices from the fields of mathematics, statistics, artificial intelligence,
and computer engineering to analyze large amounts of data."""

text2 = """Data science is the study of data to extract meaningful insights for business.
It is a multidisciplinary approach                    that combines principles and practices from the fields of              mathematics, statistics, artificial intelligence,
and computer engineering to analyze large amounts of data."""

text_list = text2.split('\n')
for line in text_list:
  list1 = []
  print('Line:',line.upper())
  if not line.isspace():
    list1.append(line)
  print(line.isspace())
  if line.isspace():
    print("line contains only space")
  else:
    print(line)

new_text = '\n'.join(list1)
print(new_text)

# zfill()  >>  zero filling
string = "data"
x = string.zfill(10)
print(x)
print(len(x))

x = "java"
y = x.zfill(14)
print(y)

# center()

string = "Python"
string.center(10)

string = "Python"
string.center(20)

string = "Python"
string.center(20,"*")

string = "Data science"
string.center(50,"*")

string = "Pyton and data science and Ml and python"
string = string.upper()
string.count('P')

