# -*- coding: utf-8 -*-
"""Vel_Regular_expression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1jqU4BPzPeqnDfTVIaj_jKZLGIbQZwc
"""

# Regular Expression
# Regular expression is sequence of characters that forms search pattern
# Regular expression is used to find perticular pattern from given string



# Regular Expression >>RegEx
# we can use regular expression only on text data
# we can not use regular expression on images data



# use cases of RegEx:
# 1.Information or attributes extraction from text data
# 2.Text preprocessing
# 3. web scraping

# NLP >> text processing

import re

# image > Text

# Optical Character Recognition:
  #1.pytesseract
  #2.Goggle Vision
  #3.Amazon Textract
  #4.Easy-OCR

# pdf >> image >> text >> re

# pdf >> image:
  # pdf2image

# pdf >> text(Readable pdf)
#    pdftotext
#    PyPDF2
#    tabula-py
#    camelot

# pdf >> image >> text >> re( NLP Technique)

# Attributes:

# Mobile Number
# PAN Number
# Date
# Aadhar Number
# DL Number
# IFSC Code
# Account Number
# email Id

# Regular Expression Function

# re.findall()   >> list
# re.sub()       >> string
# re.match()     >> objects
# re.search()    >> objects
# re.compile()   >> pattern objects
# re.split()     >> list

# findall

# re.findall(pattern,text)
# pattern >> str
# text >> str

# Return >> List of all matches

# Special sequence

# \d  >> [0-9]
# \D  >> [^0-9]
# \w  >> [0-9a-zA-Z_]
# \W  >> [^0-9a-zA-Z_]
# \s  >> [ ]
# \S  >> [^ ]
# \b  >> To bind pattern

# Characters with Special Meaning

# plus(+)   >> one or more occurances
# star(*)   >> zero or more occurances
# dot(.)    >> Any character except new line
# question mark(?)  >> zero or one occurances
# startswith(^)
# endswith($)
# or(|)
# ()   >> Group of char
# {}   >> Number of occurances
# []   >> set of characters

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29/05/2001"""

mobile_no = re.findall('[0-9]{10}',text)
mobile_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29/05/2001"""

result = re.findall('[0-9]{4}',text)
result

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29/05/2001"""

result = re.findall('[0-9]{5}',text)
result

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29/05/2001"""

result = re.findall('[0-9]{3}',text)
result

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001"""

DOB = re.findall('[0-9]{2}[-]{1}[0-9]{2}[-]{1}[0-9]{4}',text)
DOB

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001"""

DOB = re.findall('[0-9]{2}[-][0-9]{2}[-][0-9]{4}',text)
DOB

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

DOB = re.findall('[0-9]{2}[-]{1}[0-9]{2}[-]{1}[0-9]{4}',text)
DOB

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

DOB = re.findall('[0-9]{2}[-][0-9]{2}[-][0-9]{4}',text)
DOB

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

email_id = re.findall('[a-z]',text)
print(email_id)

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

email_id = re.findall('[a-z]{2}',text)
print(email_id)

text = """My mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

email_id = re.findall('[a-z]{5,20}',text)
print(email_id)

import re
text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

email_id = re.findall(r'[a-z]{5,20}[@]{1}[a-z.]{5,20}',text)
email_id

import re

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

# Modified regex pattern to be case-insensitive and handle whitespace
email_id = re.findall(r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+', text, re.IGNORECASE)
print(email_id)

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019"""

date = re.findall('[0-9]{2}[-/][0-9]{2}[-/][0-9]{4}',text)
date

import re

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwarya_satpute73@gmail.com
           aishwarya_satpute173@gmail.com
           aishwaryasatpute173@gmail.com

           rohitsharma@yahoo.com
           rohit.sharma@yahoo.com
           rohit.sharma14@yahoo.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

# Modified regex pattern to be case-insensitive and handle whitespace
email_id = re.findall(r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+', text)
print(email_id)

import re
text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVB8236K
           GHJKL8163S
           ROUYP4581B """

pan_no = re.findall('[A-Z]{5}[0-9]{4}[A-Z]',text)
pan_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581B """

pan_no = re.findall('[A-Z]{5}[0-9]{4}[A-Z]',text)
pan_no

import re
text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com """

mail_id = re.findall('[a-z0-9]{1,30}[@]{1}[a-z.]{1,15}',text)
mail_id

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581BSZXGVML """

pan_no = re.findall('[A-Z]{5}[0-9]{4}[A-Z]',text)
pan_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581BSZXGVML   # Invalid """

pan_no = re.findall(r'\b[A-Z]{5}[0-9]{4}[A-Z]\b',text)
pan_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581BSZXGVML   # Invalid

           Aadhar nos:
           3674 8420 8429
           4783 9307 9435
           7429 8382 9092
           """

aadhar_no = re.findall('[0-9]{4}[ ][0-9]{4}[ ][0-9]{4}',text)
aadhar_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581BSZXGVML   # Invalid

           Aadhar nos:
           4715 9307 9435
           1551 8382 9092
           1574 8420 8429
           """

aadhar_no = re.findall('[15]{4}[ ][0-9]{4}[ ][0-9]{4}',text)
aadhar_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581BSZXGVML   # Invalid

           Aadhar nos:
           4715 9307 9435
           1551 8382 9092
           1334 8420 8429
           """

aadhar_no = re.findall('[1543]{4}[ ][0-9]{4}[ ][0-9]{4}',text)
aadhar_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-1995
           21-07-1947
           14-02-2020
           21-04-2209

           """

dob = re.findall('[0-9]{2}[-][0-9]{2}[-][0-9]{4}',text)
dob

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-1995
           21-07-1947
           14-02-2020
           21-04-2209

           """

dob = re.findall('[0-9]{2}[-][0-9]{2}[-][1910]{2}',text)
dob

# special sequence

# \d  >> [0-9]

text = """My mobile Numbers are:
        1. 5833853883
        2. 4389498358

        Email ID is:
        aishwaryasatpute61@gmail.com

        DOB:
        21-05-2001
        17-06-2003
        23-09-1998
        19-02-1994"""

date = re.findall('[0-9]{2}[-][0-9]{2}[-][0-9]{4}',text)
date

text = """My mobile Numbers are:
        1. 5833853883
        2. 4389498358

        Email ID is:
        aishwaryasatpute61@gmail.com

        DOB:
        21-05-2001
        17-06-2003
        23-09-1998
        19-02-1994"""

date = re.findall('\d{2}[-]\d{2}[-]\d{4}',text)
date

text = """My mobile Numbers are:
        1. 5833853883
        2. 4389498358

        Email ID is:
        aishwaryasatpute61@gmail.com

        DOB:
        21-05-2001
        17-06-2003
        23-09-1998
        19-02-1994"""

date = re.findall('\d{10}',text)
date

text = """Aadhar Numbers:
          3289 4897 3897
          2847 9420 4828
          2498 4898 4490
          3824 8282 8348"""

aadhar_numbers = re.findall('[0-9]{4}[ ][0-9]{4}[ ][0-9]{4}',text)
aadhar_numbers

text = """Aadhar Numbers:
          3289 4897 3897
          2847 9420 4828
          2498 4898 4490
          3824 8282 8348"""

aadhar_numbers = re.findall('\d{4}[ ]\d{4}[ ]\d{4}',text)
aadhar_numbers

# \D >> Except [0-9]
# \D >> [^0-9]

text = """My mobile Numbers are:
        1. 5833853883
        2. 4389498358

        Email ID is:
        aishwaryasatpute61@gmail.com

        DOB:
        21-05-2001 """

mbl_no = re.findall('[^0-9]{10}',text)
mbl_no

text = """My mobile Numbers are:
        1. 5833853883
        2. 4389498358

        Email ID is:
        aishwaryasatpute61@gmail.com

        DOB:
        21-05-2001 """

mbl_no = re.findall('[^0-9]{1}',text)
mbl_no

# \w >> '[a-zA-Z0-9_]'

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwarya_satpute73@gmail.com
           aishwarya_satpute173@gmail.com
           aishwaryasatpute173@gmail.com

           rohitsharma@yahoo.com
           rohit.sharma@yahoo.com
           rohit.sharma14@yahoo.com

           Date of Birth is: 29-05-2001
           21-07-2004
           14-02-1995"""

email_id = re.findall('\w{5,20}[@][a-z.]{5,20}',text)
email_id

ds = """Data science is the study of data to extract 64y46 meaningful insights for business.
It is a multidisciplinary approach that combines principles and practices from the fields of mathematics,
statistics, artificial intelligence, and computer engineering to analyze large amounts of data."""

result = re.findall('[a-zA-Z0-9]{5}',ds)
print(result)

ds = """Data science is the study of data to extract 64y46 meaningful insights for business.
It is a multidisciplinary approach that combines principles and practices from the fields of mathematics,
statistics, artificial intelligence, and computer engineering to analyze large amounts of data."""

result = re.findall('\w{5}',ds)
print(result)

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com

           DateofBirth is: 29-05-2001"""

mbl_no = re.findall('\w{10}',text)
mbl_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581B SZXGVML"""   # Invalid



pan_no = re.findall('[A-Z]{5}[0-9]{4}[A-Z]',text)
pan_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581B SZXGVML"""   # Invalid



pan_no = re.findall(r'\b[A-Z]{5}[0-9]{4}[A-Z]\b',text)
pan_no

text = """My Mobile Numbers are:
           1. 3587984095
           2. 5875762905

           Email ID is:
           aishwaryasatpute34@gmail.com
           aishwaryasatpute73@gmail.com

           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG2635H
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581B SZXGVML"""   # Invalid



pan_no = re.findall(r'\b\w{10}\b',text)
pan_no

# \W  >> except '[a-zA-Z0-9_]'
# \W  >> '[^a-zA-Z0-9_]'

text = """text no:
          3244 4533 3453
          5532 3453 3532
          4455 5563 6545
          4355 5245 4662"""

aadhar_no = re.findall('[0-9]{4}[ ][0-9]{4}[ ][0-9]{4}',text)
aadhar_no

# \s >> space

text = """text no:
          3244 4533 3453
          5532 3453 3532
          4455 5563 6545
          4355 5245 4662"""

aadhar_no = re.findall('\d{4}\s\d{4}\s\d{4}',text)
aadhar_no

# \S >> Except space
text = """text no:
          3244 4533 3453
          5532 3453 3532
          4455 5563 6545
          4355 5245 4662"""

aadhar_no = re.findall('\S',text)
aadhar_no

text = """text no:
          3244 4533 3453
          5532 3453 3532
          4455 5563 6545
          4355 5245 4662"""

aadhar_no = re.findall('\S{4}',text)
aadhar_no

text = """Aadhar Numbers:
          4389 3589 3984
          3909 8349 3893
   22427463773 8353 8922

          4891 9390 8938
          2899 4338 3902039034
          2984 8428 4838EFVDKL
           """

aadhar_no = re.findall('\d{4}\s\d{4}\s\d{4}',text)
aadhar_no

text = """Aadhar Numbers:
          4389 3589 3984
          3909 8349 3893
   22427463773 8353 8922   # invalid

          4891 9390 8938
          2899 4338 3902039034
          2984 8428 4838EFVDKL
           """

aadhar_no = re.findall(r'\b\d{4}\s\d{4}\s\d{4}',text)
aadhar_no

text = """Aadhar Numbers:
          4389 3589 3984
          3909 8349 3893
   22427463773 8353 8922   # invalid

          4891 9390 8938
          2899 4338 3902039034  # invalid
          2984 8428 4838EFVDKL  # invalid
           """

aadhar_no = re.findall(r'\b\d{4}\s\d{4}\s\d{4}\b',text)
aadhar_no

text = """My Mobile Number are:
          1. 1783891421
          2. 8232970202

          Account Numbers:
          39057954690740
          439704737843
          2089424449220492 """

mbl_no = re.findall(r'\b[0-9]{10}\b',text)
mbl_no

pip install pytesseract

import pytesseract

# text = pytesseract.image_to_string('pacard.jpg')
# print(text)

# \W >> except '[0-9a-zA-Z_]'
# \W >> '[^ 0-9a-zA-Z_]'

text = """
           Dates:
           29-05-2001
           21-07-2004
           14-02-1995
           21/04/2019

           PAN Card nos:
           QWERT4567T
           ASDFG26359H  # Invalid
           ZXCVBK236K  # Invalid
           GHJKL8163S
           ROUYP4581B SZXGVML"""   # Invalid

pan_no = re.findall('\W{1}',text)
pan_no

# Regular Expression
import re

# Regular Expression Functions

# re.findall()

text = "Data Science"
result = re.findall('[a-zA-Z]{7}',text)
result

# re.sub()

# re.sub(old_substring_pattern,new_substring_pattern)

string = "python and data science"
string.replace("python","java")

string = " 487 python and  68 data science 48792"
string.replace("487",'')

string = " 487 python and  68 data science 48792"
string.replace("487",'').replace("92",'')

string = "python and data science"
re.sub("python","JAVA",string)

string = "2746 python and 38859 data 378 science 29"
re.sub('[0-9]','',string)

string = "2746 $% python and ^&*! 38859 data &!~+: science 29"
re.sub('[^a-zA-Z ]','',string)

import re
string = "2746 $% python and ^&*! 38859 data &!~+: science 29"
re.sub('[^a-zA-Z]','',string)

string = "698 python 853 and data science %^@# 234"
re.sub('[^a-zA-Z]','',string)

string = "698 python 853 and data science %^@# 234"
re.sub('[^a-zA-Z]',' ',string)

string = "698 python 853 and data science %^@# 234"
re.sub('[^a-zA-Z]+',' ',string) # one or more occurances

# "689" >> " "
# "853" >> " "
# " %^@# "  >> " "
# "234"  >> " "

string = "698 python 853 and data science %^@# 234"
re.sub('[^a-zA-Z]+',' ',string).strip()     # remove all leading and trailing white spaces

f = open("/content/re.txt")
text = f.read()
print(text)

result =  re.sub('[^a-zA-Z]',' ',text)
result

result =  re.sub('[^a-zA-Z]+',' ',text)
result

result =  re.sub('[^a-zA-Z]+',' ',text)
result = re.sub(r'\b[a-zA-Z]\b',' ',result)
print(result)

result =  re.sub('[^a-zA-Z]+',' ',text)
result = re.sub(r'\b[a-zA-Z]\b',' ',result)
result = re.sub('\s+',' ',result)
print(result)

# Characters with special meaning

# Plus(+)
# + >> one or more occurance

string = "663 python and *#$% data 89 science 347 #^^!*%"
result = re.sub('[^a-zA-Z ]','',string).strip()
result

string = "663 python and *#$% data 89 science 347 #^^!*%"
result = re.sub('[^a-zA-Z]+',' ',string).strip()   # one or more occurance
result

text = "python              and    data        science"
result = re.sub('\s+',' ',text)     # replace one or more spaces with single spaces
result

text = "python and data science pytttthon pyttthon pythhhhon python"
result = re.findall('python',text)
result

text = "python and data science pytttthon pyttthon pythhhhon python"
result = re.findall('pyt+hon',text)
result

text = "python and data science pytttthon pyttthon pythhhhon python"
result = re.findall('pyth+on',text)
result

text = "python and data science pytttthon pyttthon pythhhhon python"
result = re.findall('pyt+h+on',text)
result

# star(*)  >> zero or more occurances
import re
text = "python and data science pytttthon pyttthon pythhhhon pyhon"
result = re.findall('pyt*hon',text)
result

import re
text = "python and data science pytttthon pyttthon pythhhhon pyhon"
result = re.findall('pyt*h+on',text)
result

text = "python and data science pytttthon pyttthon pythhhhon python pyhon"
result = re.findall('pyt*hon',text)
result

text = "python and data science pytttthon pyttthon pythhhhon  pyhon"
result = re.findall('pyt*h+on',text)
result

#dot(.) >> any character except new line

text = "python and data science pytttthon pyttthon pythhhhon  pyhon"
result = re.findall("python",text)
result

text = "python and data science pytttthon pyttthon pythhhhon pyrhon"
result = re.findall("py.hon",text)
result

text = "python and data science pytttthon pyttthon pythhhhon pyrhon"
result = re.findall("py.*hon",text)
result

text = "pyttthon and data science pytttthon pyttthon pythhhhon pyhon"
result = re.findall("py.hon",text)
result

text = "pyttthon and data science pytttthon pyttthon pythhhhon python"
result = re.findall("py..on",text)
result

string = """
         9924438720
         9283099650
         3098935409
         2845938382
         4892843378
         9932484200
         9459546045 """

result = re.findall("99........",string)
result

string = """
         9924438720
         9283099650
         3098935409
         2845938382
         4892843378
         9932484200
         9459546045 """

result = re.findall("99......20",string)
result

string = """
         9924438720
         9283099650
         3098935409
         2845938382
         4892843378
         9932484200
         9459546045 """

result = re.findall("99.......0",string)
result

string = """
         9924438730
         9283099650
         3098935409
         2845938382
         4892843378
         9932484230
         9459546045 """

result = re.findall("........30",string)
result

string = """
         9924438730
         9283099650
         3098935409
         2845938382
         4892843378
         9932484230
         9459546045 """

result = re.findall(r"\b........30\b",string)
result

# Question Mark(?)
# ? >> It matches exactly zero or one occurrence

text = "pyttthon and data science pytttthon pyttthon pythhhhon python"
result = re.findall('python',text)
result

text = "pyttthon and data science pyton pyhon pythhhhon python"
result = re.findall('pyt+h+on',text)
result

text = "pyttthon and data science pytttthon pyttthon pythhhhon python"
result = re.findall('pyt*h*on',text)
result

text = "pyttthon and data science pyhon pyttthon pyton python"
result = re.findall('pyt?h?on',text)
result

text = 'batman and batwoman batwwwwwoman'
result = re.findall('batw?o?man',text)
result

# startswith(^)

text = '1. batman and batwoman'
result = re.findall('^1',text)
if result:
  print("string is started with expected pattern")

text = '2. batman and batwoman'
result = re.findall('^[0-9]',text)
result

text = '3. batman and batwoman'
result = re.findall('^\d',text)
result

text = 'python and data science'
result = re.findall('^[a-zA-Z]',text)
result

text = 'python and data science'
result = re.findall('^[pds]',text)
result

text = 'data science and ML'
result = re.findall('^[pds]',text)
result

text = '1.data science and ML'
result = re.findall('^[a-zA-Z0-9]',text)
result

# endswith($)

text = 'data science and Machine learning'
result = re.findall('learning$',text)
result

text = 'data science and Machine learning'
result = re.findall('learning$$',text)
result

text = 'data science and Machine learning '
result = re.findall('learning$',text)
result

text = 'data science and machine'
result = re.findall('machine$',text)
result

text = 'data science and machine'
result = re.findall('[a-zA-Z]$',text)
result

text = 'data science and machine learning'
result = re.findall('[a-zA-Z]$',text)
result

text = 'data science and machine learning'
result = re.findall('^dg$',text)
result

text = 'data science and machine learning'
result = re.findall('^d.+g$',text)
result

# or(|)

text = "data science and machine learning"
result = re.findall("data|machine",text)
result

text = "data science and machine learning"
result = re.findall("data|machine|science",text)
result

text = "data science and deep learning"
result = re.findall("data|machine|science",text)
result

text = "data science and deep learning"
result = re.findall("[a-z]{4}|[a-z]{7}",text)
result

text = "data science and deep learning"
result = re.findall(r"\b[a-z]{4}\b",text)
result

text = "data science and deep learning"
result = re.findall(r"\b[a-z]{4}\b|\b[a-z]{7}\b",text)
result

string = """
         22-09-2022
         29/09/2022
         22.09.2020
         15-05-2009
         25 Jan 2008
         19/04/2001"""

dates = re.findall("[0-9]{2}[-][0-9]{2}[-][0-9]{4}",string)
dates

string = """
         22-09-2022
         29/09/2022
         22.09.2020
         15-05-2009
         25 Jan 2008
         19/04/2001"""

dates = re.findall("[0-9]{2}[-/][0-9]{2}[-/][0-9]{4}",string)
dates

string = """
         22-09-2022
         29/09/2022
         22.09.2020
         15-05-2009
         25 Jan 2008
         19/04/2001"""

dates = re.findall("[0-9]{2}[-/.][0-9]{2}[-/.][0-9]{4}",string)
dates

string = """
         22-09-2022
         29/09/2022
         22.09.2020
         15-05-2009
         25 Jan 2008
         19/04/2001"""

dates = re.findall("[0-9]{2}[-/.][0-9]{2}[-/.][0-9]{4}|[0-9]{2}\s[A-Z][a-z]{2}\s\d{4}",string)
dates

# Group of chars >> ()

# ()  >> Used to find group of char

# re.search()  >> It returns an object of first occurance only

import re
string = """
          (+91) 7656543696
          (+91) 5904348756
          3857296471"""

result = re.findall('\d{10}',string)
result

string = """
          (+91) 7656543696
          (+91) 5904348756
          3857296471"""

result = re.search('\d{10}',string)
result

string = """
          (+91) 7656543696
          (+91) 5904348756
          3857296471"""

mbl_no = re.search('\d{10}',string)
mbl_no.group()

string = """
          (+91) 7656543696
          (+91) 5904348756
          38572964714"""

mbl_no = re.search('\d{11}', string)
if mbl_no:
    print(mbl_no.group())
else:
    print("No match found.")

string = """
          (+91) 7656543696
          (+91) 5904348756785
          3857296471"""

mbl_no = re.search('\d{11}',string)
if mbl_no:
  print(mbl_no.group())

string = """
          (+91) 7656543696
          (+91)    5904348756785
          3857296471"""

mbl_no = re.search('\d{11}',string)
if mbl_no:
  print(mbl_no.group())
  print(mbl_no.start())
  print(mbl_no.end())
  print(mbl_no.span())

text = "data science and deep learning"
result = re.search("data|machine|science",text)
result

text = "data science and deep learning"
result = re.search("data|machine|science",text)
if result:
  print(result.group())
  print(result.start())
  print(result.end())
  print(result.span())

# match

# Match function searches for match at the begining of the string and return an object

text = "data science and deep learning"
result = re.search('data|machine|science',text)
if result:
  print(result.group())
  print(result.start())
  print(result.end())
  print(result.span())

text = "data science and deep learning"
result = re.search('[a-z]+',text)
if result:
  print(result.group())
  print(result.start())
  print(result.end())
  print(result.span())

# compile

string1 = "934-282-7868"
string2 = "769-7790"
string3 = "298-827-0000"
string4 = "428-289-297927482"

result = re.search('\d{3}[-]\d{3}[-]\d{4}',string1)
if result:
    print(result.group())
else:
    print("No match found.")

string1 = "934-282-7868"
string2 = "769-7790"
string3 = "298-827-0000"
string4 = "428-289-297927482"

result1 = re.search('\d{3}[-]\d{3}[-]\d{4}',string1)
result1.group()

result2 = re.search('\d{3}[-]\d{4}',string2)
result2.group()

# result3 = re.search('\d{3}[-]\d{3}[-]\d{4}',string3)
# result3.group()

result4 = re.search('\d{3}[-]\d{3}[-]\d{9}',string4)
result4.group()

string1 = "934-282-7868"
string2 = "769-7790"
string3 = "298-827-0000"
string4 = "428-289-297927482"

result1 = re.search('\d{3}[-]\d{3}[-]\d{4}',string1)
result1.group()

result2 = re.search('\d{3}[-]\d{4}',string2)
result2.group()

# result3 = re.search('\d{3}[-]\d{3}[-]\d{4}',string3)
# result3.group()

result4 = re.search('\d{3}[-]\d{3}[-]\d{4}',string4)
result4.group()

pattern = re.compile('(\d{3}[-])?\d{3}[-]\d{4}')
pattern

pattern = re.compile('(\d{3}[-])?\d{3}[-]\d{4}')
result = pattern.search(string1)
print(result1.group())

pattern = re.compile('(\d{3}[-])?\d{3}[-]\d{4}')
result1 = pattern.search(string1)
result2 = pattern.search(string2)

print(result1.group())
print(result2.group())

string = "Data science and machine learning 100"
string.split()

string = "Data science 1 and machine learning 2 and deep learning 3"
string.split()

string = "Data science 1 and machine learning 1 and deep learning 3"
string.split('1')

string = "Data science and machine learning and deep learning"
string.split('and')

import re
string = "Data 1 science and machine 2 learning and deep 3 learning"
re.split('[0-9]',string)

import re
string = "23-87-52-93-66-68-31"
re.split('[-]',string)

import re
string = "23-87-52-93-66,85,76,69,53,28,61-68-31"
re.split('[-]',string)

import re
string = "23-87-52-93-66,85,76,69,53,28,61-68-31"
re.split('[-,]',string)

!pip install pytesseract
import pytesseract

